package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * CmdExecute generated by hbm2java
 */
public class CmdExecute implements java.io.Serializable
{

	private Long cmdExecuteId;
	private CmdRequest cmdRequest;
	private String cmdExecuteHost;
	private Date cmdExecuteTime;
	private String cmdExecuteCode;
	private String cmdExecuteMsg;
	private int cmdExecuteExitStatus;
	private String cmdExecuteStderr;
	private String cmdExecuteStdout;
	private int cmdExecuteState;

	public CmdExecute()
	{
	}

	public CmdExecute(String cmdExecuteHost, Date cmdExecuteTime, String cmdExecuteCode, String cmdExecuteMsg, int cmdExecuteExitStatus, String cmdExecuteStderr, String cmdExecuteStdout, int cmdExecuteState)
	{
		this.cmdExecuteHost = cmdExecuteHost;
		this.cmdExecuteTime = cmdExecuteTime;
		this.cmdExecuteCode = cmdExecuteCode;
		this.cmdExecuteMsg = cmdExecuteMsg;
		this.cmdExecuteExitStatus = cmdExecuteExitStatus;
		this.cmdExecuteStderr = cmdExecuteStderr;
		this.cmdExecuteStdout = cmdExecuteStdout;
		this.cmdExecuteState = cmdExecuteState;
	}

	public CmdExecute(CmdRequest cmdRequest, String cmdExecuteHost, Date cmdExecuteTime, String cmdExecuteCode, String cmdExecuteMsg, int cmdExecuteExitStatus, String cmdExecuteStderr, String cmdExecuteStdout, int cmdExecuteState)
	{
		this.cmdRequest = cmdRequest;
		this.cmdExecuteHost = cmdExecuteHost;
		this.cmdExecuteTime = cmdExecuteTime;
		this.cmdExecuteCode = cmdExecuteCode;
		this.cmdExecuteMsg = cmdExecuteMsg;
		this.cmdExecuteExitStatus = cmdExecuteExitStatus;
		this.cmdExecuteStderr = cmdExecuteStderr;
		this.cmdExecuteStdout = cmdExecuteStdout;
		this.cmdExecuteState = cmdExecuteState;
	}

	public Long getCmdExecuteId()
	{
		return this.cmdExecuteId;
	}

	public void setCmdExecuteId(Long cmdExecuteId)
	{
		this.cmdExecuteId = cmdExecuteId;
	}

	public CmdRequest getCmdRequest()
	{
		return this.cmdRequest;
	}

	public void setCmdRequest(CmdRequest cmdRequest)
	{
		this.cmdRequest = cmdRequest;
	}

	public String getCmdExecuteHost()
	{
		return this.cmdExecuteHost;
	}

	public void setCmdExecuteHost(String cmdExecuteHost)
	{
		this.cmdExecuteHost = cmdExecuteHost;
	}

	public Date getCmdExecuteTime()
	{
		return this.cmdExecuteTime;
	}

	public void setCmdExecuteTime(Date cmdExecuteTime)
	{
		this.cmdExecuteTime = cmdExecuteTime;
	}

	public String getCmdExecuteCode()
	{
		return this.cmdExecuteCode;
	}

	public void setCmdExecuteCode(String cmdExecuteCode)
	{
		this.cmdExecuteCode = cmdExecuteCode;
	}

	public String getCmdExecuteMsg()
	{
		return this.cmdExecuteMsg;
	}

	public void setCmdExecuteMsg(String cmdExecuteMsg)
	{
		this.cmdExecuteMsg = cmdExecuteMsg;
	}

	public int getCmdExecuteExitStatus()
	{
		return this.cmdExecuteExitStatus;
	}

	public void setCmdExecuteExitStatus(int cmdExecuteExitStatus)
	{
		this.cmdExecuteExitStatus = cmdExecuteExitStatus;
	}

	public String getCmdExecuteStderr()
	{
		return this.cmdExecuteStderr;
	}

	public void setCmdExecuteStderr(String cmdExecuteStderr)
	{
		this.cmdExecuteStderr = cmdExecuteStderr;
	}

	public String getCmdExecuteStdout()
	{
		return this.cmdExecuteStdout;
	}

	public void setCmdExecuteStdout(String cmdExecuteStdout)
	{
		this.cmdExecuteStdout = cmdExecuteStdout;
	}

	public int getCmdExecuteState()
	{
		return this.cmdExecuteState;
	}

	public void setCmdExecuteState(int cmdExecuteState)
	{
		this.cmdExecuteState = cmdExecuteState;
	}

}
