package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CmdRequest generated by hbm2java
 */
public class CmdRequest implements java.io.Serializable
{

	private Long cmdRequestId;
	private HpcCluster hpcCluster;
	private Date cmdRequestTime;
	private String cmdRequestUsername;
	private String cmdRequestCmdline;
	private String cmdRequestStdin;
	private String cmdRequestHostType;
	private String cmdRequestHostExpr;
	private int cmdRequestState;
	private Set cmdExecutes = new HashSet(0);

	public CmdRequest()
	{
	}

	public CmdRequest(Date cmdRequestTime, String cmdRequestUsername, String cmdRequestCmdline, String cmdRequestStdin, String cmdRequestHostType, int cmdRequestState)
	{
		this.cmdRequestTime = cmdRequestTime;
		this.cmdRequestUsername = cmdRequestUsername;
		this.cmdRequestCmdline = cmdRequestCmdline;
		this.cmdRequestStdin = cmdRequestStdin;
		this.cmdRequestHostType = cmdRequestHostType;
		this.cmdRequestState = cmdRequestState;
	}

	public CmdRequest(HpcCluster hpcCluster, Date cmdRequestTime, String cmdRequestUsername, String cmdRequestCmdline, String cmdRequestStdin, String cmdRequestHostType, String cmdRequestHostExpr, int cmdRequestState, Set cmdExecutes)
	{
		this.hpcCluster = hpcCluster;
		this.cmdRequestTime = cmdRequestTime;
		this.cmdRequestUsername = cmdRequestUsername;
		this.cmdRequestCmdline = cmdRequestCmdline;
		this.cmdRequestStdin = cmdRequestStdin;
		this.cmdRequestHostType = cmdRequestHostType;
		this.cmdRequestHostExpr = cmdRequestHostExpr;
		this.cmdRequestState = cmdRequestState;
		this.cmdExecutes = cmdExecutes;
	}

	public Long getCmdRequestId()
	{
		return this.cmdRequestId;
	}

	public void setCmdRequestId(Long cmdRequestId)
	{
		this.cmdRequestId = cmdRequestId;
	}

	public HpcCluster getHpcCluster()
	{
		return this.hpcCluster;
	}

	public void setHpcCluster(HpcCluster hpcCluster)
	{
		this.hpcCluster = hpcCluster;
	}

	public Date getCmdRequestTime()
	{
		return this.cmdRequestTime;
	}

	public void setCmdRequestTime(Date cmdRequestTime)
	{
		this.cmdRequestTime = cmdRequestTime;
	}

	public String getCmdRequestUsername()
	{
		return this.cmdRequestUsername;
	}

	public void setCmdRequestUsername(String cmdRequestUsername)
	{
		this.cmdRequestUsername = cmdRequestUsername;
	}

	public String getCmdRequestCmdline()
	{
		return this.cmdRequestCmdline;
	}

	public void setCmdRequestCmdline(String cmdRequestCmdline)
	{
		this.cmdRequestCmdline = cmdRequestCmdline;
	}

	public String getCmdRequestStdin()
	{
		return this.cmdRequestStdin;
	}

	public void setCmdRequestStdin(String cmdRequestStdin)
	{
		this.cmdRequestStdin = cmdRequestStdin;
	}

	public String getCmdRequestHostType()
	{
		return this.cmdRequestHostType;
	}

	public void setCmdRequestHostType(String cmdRequestHostType)
	{
		this.cmdRequestHostType = cmdRequestHostType;
	}

	public String getCmdRequestHostExpr()
	{
		return this.cmdRequestHostExpr;
	}

	public void setCmdRequestHostExpr(String cmdRequestHostExpr)
	{
		this.cmdRequestHostExpr = cmdRequestHostExpr;
	}

	public int getCmdRequestState()
	{
		return this.cmdRequestState;
	}

	public void setCmdRequestState(int cmdRequestState)
	{
		this.cmdRequestState = cmdRequestState;
	}

	public Set getCmdExecutes()
	{
		return this.cmdExecutes;
	}

	public void setCmdExecutes(Set cmdExecutes)
	{
		this.cmdExecutes = cmdExecutes;
	}

}
