package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ColInfo generated by hbm2java
 */
public class ColInfo implements java.io.Serializable
{

	private Long colInfoId;
	private ColBatch colBatch;
	private String colHostname;
	private Date colInfoTimestamp;
	private String colInfoIp;
	private String colInfoPowerType;
	private String colInfoPowerCommand;
	private String colInfoPowerUser;
	private String colInfoPowerPass;
	private char colInfoPowerStatus;
	private String colInfoPowerIdentifier;
	private String colInfoPowerIp;
	private String colInfoPowerNetmask;
	private String colInfoPowerGateway;
	private String colInfoPowerHostnamealias;
	private String colInfoState;
	private String colInfoStep;
	private String colInfoMessage;
	private char colInfoCleanbusy;
	private String colBiosVender;
	private String colBiosVersion;
	private String colBiosReleaseDate;
	private String colSysManufacturer;
	private String colSysProductName;
	private String colSysVersion;
	private String colSysSerialNumber;
	private String colSysUuid;
	private String colBaseboardManufacturer;
	private String colBaseboardProductName;
	private String colBaseboardVersion;
	private String colBaseboardSerialNumber;
	private String colChassisManufacturer;
	private String colChassisType;
	private String colChassisLock;
	private String colChassisVersion;
	private String colChassisSerialNumber;
	private Set colNets = new HashSet(0);

	public ColInfo()
	{
	}

	public ColInfo(String colHostname, Date colInfoTimestamp, String colInfoIp, char colInfoPowerStatus, String colInfoState, String colInfoStep, char colInfoCleanbusy)
	{
		this.colHostname = colHostname;
		this.colInfoTimestamp = colInfoTimestamp;
		this.colInfoIp = colInfoIp;
		this.colInfoPowerStatus = colInfoPowerStatus;
		this.colInfoState = colInfoState;
		this.colInfoStep = colInfoStep;
		this.colInfoCleanbusy = colInfoCleanbusy;
	}

	public ColInfo(ColBatch colBatch, String colHostname, Date colInfoTimestamp, String colInfoIp, String colInfoPowerType, String colInfoPowerCommand, String colInfoPowerUser, String colInfoPowerPass, char colInfoPowerStatus, String colInfoPowerIdentifier, String colInfoPowerIp,
			String colInfoPowerNetmask, String colInfoPowerGateway, String colInfoPowerHostnamealias, String colInfoState, String colInfoStep, String colInfoMessage, char colInfoCleanbusy, String colBiosVender, String colBiosVersion, String colBiosReleaseDate,
			String colSysManufacturer, String colSysProductName, String colSysVersion, String colSysSerialNumber, String colSysUuid, String colBaseboardManufacturer, String colBaseboardProductName, String colBaseboardVersion, String colBaseboardSerialNumber,
			String colChassisManufacturer, String colChassisType, String colChassisLock, String colChassisVersion, String colChassisSerialNumber, Set colNets)
	{
		this.colBatch = colBatch;
		this.colHostname = colHostname;
		this.colInfoTimestamp = colInfoTimestamp;
		this.colInfoIp = colInfoIp;
		this.colInfoPowerType = colInfoPowerType;
		this.colInfoPowerCommand = colInfoPowerCommand;
		this.colInfoPowerUser = colInfoPowerUser;
		this.colInfoPowerPass = colInfoPowerPass;
		this.colInfoPowerStatus = colInfoPowerStatus;
		this.colInfoPowerIdentifier = colInfoPowerIdentifier;
		this.colInfoPowerIp = colInfoPowerIp;
		this.colInfoPowerNetmask = colInfoPowerNetmask;
		this.colInfoPowerGateway = colInfoPowerGateway;
		this.colInfoPowerHostnamealias = colInfoPowerHostnamealias;
		this.colInfoState = colInfoState;
		this.colInfoStep = colInfoStep;
		this.colInfoMessage = colInfoMessage;
		this.colInfoCleanbusy = colInfoCleanbusy;
		this.colBiosVender = colBiosVender;
		this.colBiosVersion = colBiosVersion;
		this.colBiosReleaseDate = colBiosReleaseDate;
		this.colSysManufacturer = colSysManufacturer;
		this.colSysProductName = colSysProductName;
		this.colSysVersion = colSysVersion;
		this.colSysSerialNumber = colSysSerialNumber;
		this.colSysUuid = colSysUuid;
		this.colBaseboardManufacturer = colBaseboardManufacturer;
		this.colBaseboardProductName = colBaseboardProductName;
		this.colBaseboardVersion = colBaseboardVersion;
		this.colBaseboardSerialNumber = colBaseboardSerialNumber;
		this.colChassisManufacturer = colChassisManufacturer;
		this.colChassisType = colChassisType;
		this.colChassisLock = colChassisLock;
		this.colChassisVersion = colChassisVersion;
		this.colChassisSerialNumber = colChassisSerialNumber;
		this.colNets = colNets;
	}

	public Long getColInfoId()
	{
		return this.colInfoId;
	}

	public void setColInfoId(Long colInfoId)
	{
		this.colInfoId = colInfoId;
	}

	public ColBatch getColBatch()
	{
		return this.colBatch;
	}

	public void setColBatch(ColBatch colBatch)
	{
		this.colBatch = colBatch;
	}

	public String getColHostname()
	{
		return this.colHostname;
	}

	public void setColHostname(String colHostname)
	{
		this.colHostname = colHostname;
	}

	public Date getColInfoTimestamp()
	{
		return this.colInfoTimestamp;
	}

	public void setColInfoTimestamp(Date colInfoTimestamp)
	{
		this.colInfoTimestamp = colInfoTimestamp;
	}

	public String getColInfoIp()
	{
		return this.colInfoIp;
	}

	public void setColInfoIp(String colInfoIp)
	{
		this.colInfoIp = colInfoIp;
	}

	public String getColInfoPowerType()
	{
		return this.colInfoPowerType;
	}

	public void setColInfoPowerType(String colInfoPowerType)
	{
		this.colInfoPowerType = colInfoPowerType;
	}

	public String getColInfoPowerCommand()
	{
		return this.colInfoPowerCommand;
	}

	public void setColInfoPowerCommand(String colInfoPowerCommand)
	{
		this.colInfoPowerCommand = colInfoPowerCommand;
	}

	public String getColInfoPowerUser()
	{
		return this.colInfoPowerUser;
	}

	public void setColInfoPowerUser(String colInfoPowerUser)
	{
		this.colInfoPowerUser = colInfoPowerUser;
	}

	public String getColInfoPowerPass()
	{
		return this.colInfoPowerPass;
	}

	public void setColInfoPowerPass(String colInfoPowerPass)
	{
		this.colInfoPowerPass = colInfoPowerPass;
	}

	public char getColInfoPowerStatus()
	{
		return this.colInfoPowerStatus;
	}

	public void setColInfoPowerStatus(char colInfoPowerStatus)
	{
		this.colInfoPowerStatus = colInfoPowerStatus;
	}

	public String getColInfoPowerIdentifier()
	{
		return this.colInfoPowerIdentifier;
	}

	public void setColInfoPowerIdentifier(String colInfoPowerIdentifier)
	{
		this.colInfoPowerIdentifier = colInfoPowerIdentifier;
	}

	public String getColInfoPowerIp()
	{
		return this.colInfoPowerIp;
	}

	public void setColInfoPowerIp(String colInfoPowerIp)
	{
		this.colInfoPowerIp = colInfoPowerIp;
	}

	public String getColInfoPowerNetmask()
	{
		return this.colInfoPowerNetmask;
	}

	public void setColInfoPowerNetmask(String colInfoPowerNetmask)
	{
		this.colInfoPowerNetmask = colInfoPowerNetmask;
	}

	public String getColInfoPowerGateway()
	{
		return this.colInfoPowerGateway;
	}

	public void setColInfoPowerGateway(String colInfoPowerGateway)
	{
		this.colInfoPowerGateway = colInfoPowerGateway;
	}

	public String getColInfoPowerHostnamealias()
	{
		return this.colInfoPowerHostnamealias;
	}

	public void setColInfoPowerHostnamealias(String colInfoPowerHostnamealias)
	{
		this.colInfoPowerHostnamealias = colInfoPowerHostnamealias;
	}

	public String getColInfoState()
	{
		return this.colInfoState;
	}

	public void setColInfoState(String colInfoState)
	{
		this.colInfoState = colInfoState;
	}

	public String getColInfoStep()
	{
		return this.colInfoStep;
	}

	public void setColInfoStep(String colInfoStep)
	{
		this.colInfoStep = colInfoStep;
	}

	public String getColInfoMessage()
	{
		return this.colInfoMessage;
	}

	public void setColInfoMessage(String colInfoMessage)
	{
		this.colInfoMessage = colInfoMessage;
	}

	public char getColInfoCleanbusy()
	{
		return this.colInfoCleanbusy;
	}

	public void setColInfoCleanbusy(char colInfoCleanbusy)
	{
		this.colInfoCleanbusy = colInfoCleanbusy;
	}

	public String getColBiosVender()
	{
		return this.colBiosVender;
	}

	public void setColBiosVender(String colBiosVender)
	{
		this.colBiosVender = colBiosVender;
	}

	public String getColBiosVersion()
	{
		return this.colBiosVersion;
	}

	public void setColBiosVersion(String colBiosVersion)
	{
		this.colBiosVersion = colBiosVersion;
	}

	public String getColBiosReleaseDate()
	{
		return this.colBiosReleaseDate;
	}

	public void setColBiosReleaseDate(String colBiosReleaseDate)
	{
		this.colBiosReleaseDate = colBiosReleaseDate;
	}

	public String getColSysManufacturer()
	{
		return this.colSysManufacturer;
	}

	public void setColSysManufacturer(String colSysManufacturer)
	{
		this.colSysManufacturer = colSysManufacturer;
	}

	public String getColSysProductName()
	{
		return this.colSysProductName;
	}

	public void setColSysProductName(String colSysProductName)
	{
		this.colSysProductName = colSysProductName;
	}

	public String getColSysVersion()
	{
		return this.colSysVersion;
	}

	public void setColSysVersion(String colSysVersion)
	{
		this.colSysVersion = colSysVersion;
	}

	public String getColSysSerialNumber()
	{
		return this.colSysSerialNumber;
	}

	public void setColSysSerialNumber(String colSysSerialNumber)
	{
		this.colSysSerialNumber = colSysSerialNumber;
	}

	public String getColSysUuid()
	{
		return this.colSysUuid;
	}

	public void setColSysUuid(String colSysUuid)
	{
		this.colSysUuid = colSysUuid;
	}

	public String getColBaseboardManufacturer()
	{
		return this.colBaseboardManufacturer;
	}

	public void setColBaseboardManufacturer(String colBaseboardManufacturer)
	{
		this.colBaseboardManufacturer = colBaseboardManufacturer;
	}

	public String getColBaseboardProductName()
	{
		return this.colBaseboardProductName;
	}

	public void setColBaseboardProductName(String colBaseboardProductName)
	{
		this.colBaseboardProductName = colBaseboardProductName;
	}

	public String getColBaseboardVersion()
	{
		return this.colBaseboardVersion;
	}

	public void setColBaseboardVersion(String colBaseboardVersion)
	{
		this.colBaseboardVersion = colBaseboardVersion;
	}

	public String getColBaseboardSerialNumber()
	{
		return this.colBaseboardSerialNumber;
	}

	public void setColBaseboardSerialNumber(String colBaseboardSerialNumber)
	{
		this.colBaseboardSerialNumber = colBaseboardSerialNumber;
	}

	public String getColChassisManufacturer()
	{
		return this.colChassisManufacturer;
	}

	public void setColChassisManufacturer(String colChassisManufacturer)
	{
		this.colChassisManufacturer = colChassisManufacturer;
	}

	public String getColChassisType()
	{
		return this.colChassisType;
	}

	public void setColChassisType(String colChassisType)
	{
		this.colChassisType = colChassisType;
	}

	public String getColChassisLock()
	{
		return this.colChassisLock;
	}

	public void setColChassisLock(String colChassisLock)
	{
		this.colChassisLock = colChassisLock;
	}

	public String getColChassisVersion()
	{
		return this.colChassisVersion;
	}

	public void setColChassisVersion(String colChassisVersion)
	{
		this.colChassisVersion = colChassisVersion;
	}

	public String getColChassisSerialNumber()
	{
		return this.colChassisSerialNumber;
	}

	public void setColChassisSerialNumber(String colChassisSerialNumber)
	{
		this.colChassisSerialNumber = colChassisSerialNumber;
	}

	public Set getColNets()
	{
		return this.colNets;
	}

	public void setColNets(Set colNets)
	{
		this.colNets = colNets;
	}

}
