package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * HpcAcl generated by hbm2java
 */
public class HpcAcl implements java.io.Serializable
{

	private Long hpcAclId;
	private String hpcAclName;
	private String hpcAclCode;
	private String hpcAclDescription;
	private Set hpcClusters = new HashSet(0);

	public HpcAcl()
	{
	}

	public HpcAcl(String hpcAclName, String hpcAclCode)
	{
		this.hpcAclName = hpcAclName;
		this.hpcAclCode = hpcAclCode;
	}

	public HpcAcl(String hpcAclName, String hpcAclCode, String hpcAclDescription, Set hpcClusters)
	{
		this.hpcAclName = hpcAclName;
		this.hpcAclCode = hpcAclCode;
		this.hpcAclDescription = hpcAclDescription;
		this.hpcClusters = hpcClusters;
	}

	public Long getHpcAclId()
	{
		return this.hpcAclId;
	}

	public void setHpcAclId(Long hpcAclId)
	{
		this.hpcAclId = hpcAclId;
	}

	public String getHpcAclName()
	{
		return this.hpcAclName;
	}

	public void setHpcAclName(String hpcAclName)
	{
		this.hpcAclName = hpcAclName;
	}

	public String getHpcAclCode()
	{
		return this.hpcAclCode;
	}

	public void setHpcAclCode(String hpcAclCode)
	{
		this.hpcAclCode = hpcAclCode;
	}

	public String getHpcAclDescription()
	{
		return this.hpcAclDescription;
	}

	public void setHpcAclDescription(String hpcAclDescription)
	{
		this.hpcAclDescription = hpcAclDescription;
	}

	public Set getHpcClusters()
	{
		return this.hpcClusters;
	}

	public void setHpcClusters(Set hpcClusters)
	{
		this.hpcClusters = hpcClusters;
	}

}
