package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * HpcAuthen generated by hbm2java
 */
public class HpcAuthen implements java.io.Serializable
{

	private Long hpcAuthenId;
	private String hpcAuthenName;
	private String hpcAuthenType;
	private String hpcAuthenCommand;
	private int hpcAuthenPort;
	private Set hpcClusters = new HashSet(0);

	public HpcAuthen()
	{
	}

	public HpcAuthen(String hpcAuthenName, String hpcAuthenType, String hpcAuthenCommand, int hpcAuthenPort)
	{
		this.hpcAuthenName = hpcAuthenName;
		this.hpcAuthenType = hpcAuthenType;
		this.hpcAuthenCommand = hpcAuthenCommand;
		this.hpcAuthenPort = hpcAuthenPort;
	}

	public HpcAuthen(String hpcAuthenName, String hpcAuthenType, String hpcAuthenCommand, int hpcAuthenPort, Set hpcClusters)
	{
		this.hpcAuthenName = hpcAuthenName;
		this.hpcAuthenType = hpcAuthenType;
		this.hpcAuthenCommand = hpcAuthenCommand;
		this.hpcAuthenPort = hpcAuthenPort;
		this.hpcClusters = hpcClusters;
	}

	public Long getHpcAuthenId()
	{
		return this.hpcAuthenId;
	}

	public void setHpcAuthenId(Long hpcAuthenId)
	{
		this.hpcAuthenId = hpcAuthenId;
	}

	public String getHpcAuthenName()
	{
		return this.hpcAuthenName;
	}

	public void setHpcAuthenName(String hpcAuthenName)
	{
		this.hpcAuthenName = hpcAuthenName;
	}

	public String getHpcAuthenType()
	{
		return this.hpcAuthenType;
	}

	public void setHpcAuthenType(String hpcAuthenType)
	{
		this.hpcAuthenType = hpcAuthenType;
	}

	public String getHpcAuthenCommand()
	{
		return this.hpcAuthenCommand;
	}

	public void setHpcAuthenCommand(String hpcAuthenCommand)
	{
		this.hpcAuthenCommand = hpcAuthenCommand;
	}

	public int getHpcAuthenPort()
	{
		return this.hpcAuthenPort;
	}

	public void setHpcAuthenPort(int hpcAuthenPort)
	{
		this.hpcAuthenPort = hpcAuthenPort;
	}

	public Set getHpcClusters()
	{
		return this.hpcClusters;
	}

	public void setHpcClusters(Set hpcClusters)
	{
		this.hpcClusters = hpcClusters;
	}

}
