package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * HpcClusterType generated by hbm2java
 */
public class HpcClusterType implements java.io.Serializable
{

	private Long hpcClusterTypeId;
	private String hpcClusterTypeName;
	private int hpcClusterTypeCode;
	private String hpcClusterTypeDesc;
	private Set hpcClusters = new HashSet(0);

	public HpcClusterType()
	{
	}

	public HpcClusterType(String hpcClusterTypeName, int hpcClusterTypeCode)
	{
		this.hpcClusterTypeName = hpcClusterTypeName;
		this.hpcClusterTypeCode = hpcClusterTypeCode;
	}

	public HpcClusterType(String hpcClusterTypeName, int hpcClusterTypeCode, String hpcClusterTypeDesc, Set hpcClusters)
	{
		this.hpcClusterTypeName = hpcClusterTypeName;
		this.hpcClusterTypeCode = hpcClusterTypeCode;
		this.hpcClusterTypeDesc = hpcClusterTypeDesc;
		this.hpcClusters = hpcClusters;
	}

	public Long getHpcClusterTypeId()
	{
		return this.hpcClusterTypeId;
	}

	public void setHpcClusterTypeId(Long hpcClusterTypeId)
	{
		this.hpcClusterTypeId = hpcClusterTypeId;
	}

	public String getHpcClusterTypeName()
	{
		return this.hpcClusterTypeName;
	}

	public void setHpcClusterTypeName(String hpcClusterTypeName)
	{
		this.hpcClusterTypeName = hpcClusterTypeName;
	}

	public int getHpcClusterTypeCode()
	{
		return this.hpcClusterTypeCode;
	}

	public void setHpcClusterTypeCode(int hpcClusterTypeCode)
	{
		this.hpcClusterTypeCode = hpcClusterTypeCode;
	}

	public String getHpcClusterTypeDesc()
	{
		return this.hpcClusterTypeDesc;
	}

	public void setHpcClusterTypeDesc(String hpcClusterTypeDesc)
	{
		this.hpcClusterTypeDesc = hpcClusterTypeDesc;
	}

	public Set getHpcClusters()
	{
		return this.hpcClusters;
	}

	public void setHpcClusters(Set hpcClusters)
	{
		this.hpcClusters = hpcClusters;
	}

}
