package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * HpcCluster generated by hbm2java
 */
public class HpcCluster implements java.io.Serializable
{

	private Long hpcClusterId;
	private HpcAcl hpcAcl;
	private HpcAuthen hpcAuthen;
	private HpcClusterType hpcClusterType;
	private HpcRm hpcRm;
	private String hpcClusterName;
	private String hpcClusterDesc;
	private Long hpcClusterDefrm;
	private String hpcClusterUsername;
	private String hpcClusterPassword;
	private String hpcClusterIdentifier;
	private String hpcClusterRealname;
	private String hpcClusterEmail;
	private String hpcClusterPhone;
	private String hpcClusterWechat;
	private Set hpcJobs = new HashSet(0);
	private Set hpcJobPrices = new HashSet(0);
	private Set colBatches = new HashSet(0);
	private Set hpcRms = new HashSet(0);
	private Set hpcResources = new HashSet(0);
	private Set cmdRequests = new HashSet(0);
	private Set hpcClusterUsers = new HashSet(0);
	private Set hpcNodes = new HashSet(0);

	public HpcCluster()
	{
	}

	public HpcCluster(String hpcClusterName, String hpcClusterUsername, String hpcClusterPassword, String hpcClusterIdentifier)
	{
		this.hpcClusterName = hpcClusterName;
		this.hpcClusterUsername = hpcClusterUsername;
		this.hpcClusterPassword = hpcClusterPassword;
		this.hpcClusterIdentifier = hpcClusterIdentifier;
	}

	public HpcCluster(HpcAcl hpcAcl, HpcAuthen hpcAuthen, HpcClusterType hpcClusterType, HpcRm hpcRm, String hpcClusterName, String hpcClusterDesc, Long hpcClusterDefrm, String hpcClusterUsername, String hpcClusterPassword, String hpcClusterIdentifier, String hpcClusterRealname,
			String hpcClusterEmail, String hpcClusterPhone, String hpcClusterWechat, Set hpcJobs, Set hpcJobPrices, Set colBatches, Set hpcRms, Set hpcResources, Set cmdRequests, Set hpcClusterUsers, Set hpcNodes)
	{
		this.hpcAcl = hpcAcl;
		this.hpcAuthen = hpcAuthen;
		this.hpcClusterType = hpcClusterType;
		this.hpcRm = hpcRm;
		this.hpcClusterName = hpcClusterName;
		this.hpcClusterDesc = hpcClusterDesc;
		this.hpcClusterDefrm = hpcClusterDefrm;
		this.hpcClusterUsername = hpcClusterUsername;
		this.hpcClusterPassword = hpcClusterPassword;
		this.hpcClusterIdentifier = hpcClusterIdentifier;
		this.hpcClusterRealname = hpcClusterRealname;
		this.hpcClusterEmail = hpcClusterEmail;
		this.hpcClusterPhone = hpcClusterPhone;
		this.hpcClusterWechat = hpcClusterWechat;
		this.hpcJobs = hpcJobs;
		this.hpcJobPrices = hpcJobPrices;
		this.colBatches = colBatches;
		this.hpcRms = hpcRms;
		this.hpcResources = hpcResources;
		this.cmdRequests = cmdRequests;
		this.hpcClusterUsers = hpcClusterUsers;
		this.hpcNodes = hpcNodes;
	}

	public Long getHpcClusterId()
	{
		return this.hpcClusterId;
	}

	public void setHpcClusterId(Long hpcClusterId)
	{
		this.hpcClusterId = hpcClusterId;
	}

	public HpcAcl getHpcAcl()
	{
		return this.hpcAcl;
	}

	public void setHpcAcl(HpcAcl hpcAcl)
	{
		this.hpcAcl = hpcAcl;
	}

	public HpcAuthen getHpcAuthen()
	{
		return this.hpcAuthen;
	}

	public void setHpcAuthen(HpcAuthen hpcAuthen)
	{
		this.hpcAuthen = hpcAuthen;
	}

	public HpcClusterType getHpcClusterType()
	{
		return this.hpcClusterType;
	}

	public void setHpcClusterType(HpcClusterType hpcClusterType)
	{
		this.hpcClusterType = hpcClusterType;
	}

	public HpcRm getHpcRm()
	{
		return this.hpcRm;
	}

	public void setHpcRm(HpcRm hpcRm)
	{
		this.hpcRm = hpcRm;
	}

	public String getHpcClusterName()
	{
		return this.hpcClusterName;
	}

	public void setHpcClusterName(String hpcClusterName)
	{
		this.hpcClusterName = hpcClusterName;
	}

	public String getHpcClusterDesc()
	{
		return this.hpcClusterDesc;
	}

	public void setHpcClusterDesc(String hpcClusterDesc)
	{
		this.hpcClusterDesc = hpcClusterDesc;
	}

	public Long getHpcClusterDefrm()
	{
		return this.hpcClusterDefrm;
	}

	public void setHpcClusterDefrm(Long hpcClusterDefrm)
	{
		this.hpcClusterDefrm = hpcClusterDefrm;
	}

	public String getHpcClusterUsername()
	{
		return this.hpcClusterUsername;
	}

	public void setHpcClusterUsername(String hpcClusterUsername)
	{
		this.hpcClusterUsername = hpcClusterUsername;
	}

	public String getHpcClusterPassword()
	{
		return this.hpcClusterPassword;
	}

	public void setHpcClusterPassword(String hpcClusterPassword)
	{
		this.hpcClusterPassword = hpcClusterPassword;
	}

	public String getHpcClusterIdentifier()
	{
		return this.hpcClusterIdentifier;
	}

	public void setHpcClusterIdentifier(String hpcClusterIdentifier)
	{
		this.hpcClusterIdentifier = hpcClusterIdentifier;
	}

	public String getHpcClusterRealname()
	{
		return this.hpcClusterRealname;
	}

	public void setHpcClusterRealname(String hpcClusterRealname)
	{
		this.hpcClusterRealname = hpcClusterRealname;
	}

	public String getHpcClusterEmail()
	{
		return this.hpcClusterEmail;
	}

	public void setHpcClusterEmail(String hpcClusterEmail)
	{
		this.hpcClusterEmail = hpcClusterEmail;
	}

	public String getHpcClusterPhone()
	{
		return this.hpcClusterPhone;
	}

	public void setHpcClusterPhone(String hpcClusterPhone)
	{
		this.hpcClusterPhone = hpcClusterPhone;
	}

	public String getHpcClusterWechat()
	{
		return this.hpcClusterWechat;
	}

	public void setHpcClusterWechat(String hpcClusterWechat)
	{
		this.hpcClusterWechat = hpcClusterWechat;
	}

	public Set getHpcJobs()
	{
		return this.hpcJobs;
	}

	public void setHpcJobs(Set hpcJobs)
	{
		this.hpcJobs = hpcJobs;
	}

	public Set getHpcJobPrices()
	{
		return this.hpcJobPrices;
	}

	public void setHpcJobPrices(Set hpcJobPrices)
	{
		this.hpcJobPrices = hpcJobPrices;
	}

	public Set getColBatches()
	{
		return this.colBatches;
	}

	public void setColBatches(Set colBatches)
	{
		this.colBatches = colBatches;
	}

	public Set getHpcRms()
	{
		return this.hpcRms;
	}

	public void setHpcRms(Set hpcRms)
	{
		this.hpcRms = hpcRms;
	}

	public Set getHpcResources()
	{
		return this.hpcResources;
	}

	public void setHpcResources(Set hpcResources)
	{
		this.hpcResources = hpcResources;
	}

	public Set getCmdRequests()
	{
		return this.cmdRequests;
	}

	public void setCmdRequests(Set cmdRequests)
	{
		this.cmdRequests = cmdRequests;
	}

	public Set getHpcClusterUsers()
	{
		return this.hpcClusterUsers;
	}

	public void setHpcClusterUsers(Set hpcClusterUsers)
	{
		this.hpcClusterUsers = hpcClusterUsers;
	}

	public Set getHpcNodes()
	{
		return this.hpcNodes;
	}

	public void setHpcNodes(Set hpcNodes)
	{
		this.hpcNodes = hpcNodes;
	}

}
