package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HpcClusterUser generated by hbm2java
 */
public class HpcClusterUser implements java.io.Serializable
{

	private Long hpcClstrUsrId;
	private HpcCloudUser hpcCloudUser;
	private HpcCluster hpcCluster;
	private String hpcClstrUsrName;
	private String hpcClstrUsrPasswd;
	private String hpcClstrUsrCrypt;
	private String hpcClstrUsrAuto;
	private String hpcClstrUsrIdrsa;
	private BigDecimal hpcClstrUsrBalance;
	private BigDecimal hpcClstrUsrCharged;
	private BigDecimal hpcClstrUsrConsumed;
	private BigDecimal hpcClstrUsrJobFee;
	private Long hpcClstrUsrJobNum;
	private Long hpcClstrUsrJobHosts;
	private Long hpcClstrUsrJobCores;
	private Date hpcClstrUsrJobTime;
	private BigDecimal hpcClstrUsrStrgFee;
	private BigDecimal hpcClstrUsrStrgCap;
	private String hpcClstrUsrStrgUnit;
	private Date hpcClstrUsrStrgTime;
	private Set hpcPayments = new HashSet(0);
	private Set hpcResLtds = new HashSet(0);
	private Set hpcJobs = new HashSet(0);

	public HpcClusterUser()
	{
	}

	public HpcClusterUser(HpcCloudUser hpcCloudUser, HpcCluster hpcCluster, String hpcClstrUsrName, String hpcClstrUsrPasswd, String hpcClstrUsrCrypt, String hpcClstrUsrAuto, String hpcClstrUsrIdrsa, BigDecimal hpcClstrUsrBalance, BigDecimal hpcClstrUsrCharged,
			BigDecimal hpcClstrUsrConsumed, BigDecimal hpcClstrUsrJobFee, Long hpcClstrUsrJobNum, Long hpcClstrUsrJobHosts, Long hpcClstrUsrJobCores, Date hpcClstrUsrJobTime, BigDecimal hpcClstrUsrStrgFee, BigDecimal hpcClstrUsrStrgCap, String hpcClstrUsrStrgUnit,
			Date hpcClstrUsrStrgTime, Set hpcPayments, Set hpcResLtds, Set hpcJobs)
	{
		this.hpcCloudUser = hpcCloudUser;
		this.hpcCluster = hpcCluster;
		this.hpcClstrUsrName = hpcClstrUsrName;
		this.hpcClstrUsrPasswd = hpcClstrUsrPasswd;
		this.hpcClstrUsrCrypt = hpcClstrUsrCrypt;
		this.hpcClstrUsrAuto = hpcClstrUsrAuto;
		this.hpcClstrUsrIdrsa = hpcClstrUsrIdrsa;
		this.hpcClstrUsrBalance = hpcClstrUsrBalance;
		this.hpcClstrUsrCharged = hpcClstrUsrCharged;
		this.hpcClstrUsrConsumed = hpcClstrUsrConsumed;
		this.hpcClstrUsrJobFee = hpcClstrUsrJobFee;
		this.hpcClstrUsrJobNum = hpcClstrUsrJobNum;
		this.hpcClstrUsrJobHosts = hpcClstrUsrJobHosts;
		this.hpcClstrUsrJobCores = hpcClstrUsrJobCores;
		this.hpcClstrUsrJobTime = hpcClstrUsrJobTime;
		this.hpcClstrUsrStrgFee = hpcClstrUsrStrgFee;
		this.hpcClstrUsrStrgCap = hpcClstrUsrStrgCap;
		this.hpcClstrUsrStrgUnit = hpcClstrUsrStrgUnit;
		this.hpcClstrUsrStrgTime = hpcClstrUsrStrgTime;
		this.hpcPayments = hpcPayments;
		this.hpcResLtds = hpcResLtds;
		this.hpcJobs = hpcJobs;
	}

	public Long getHpcClstrUsrId()
	{
		return this.hpcClstrUsrId;
	}

	public void setHpcClstrUsrId(Long hpcClstrUsrId)
	{
		this.hpcClstrUsrId = hpcClstrUsrId;
	}

	public HpcCloudUser getHpcCloudUser()
	{
		return this.hpcCloudUser;
	}

	public void setHpcCloudUser(HpcCloudUser hpcCloudUser)
	{
		this.hpcCloudUser = hpcCloudUser;
	}

	public HpcCluster getHpcCluster()
	{
		return this.hpcCluster;
	}

	public void setHpcCluster(HpcCluster hpcCluster)
	{
		this.hpcCluster = hpcCluster;
	}

	public String getHpcClstrUsrName()
	{
		return this.hpcClstrUsrName;
	}

	public void setHpcClstrUsrName(String hpcClstrUsrName)
	{
		this.hpcClstrUsrName = hpcClstrUsrName;
	}

	public String getHpcClstrUsrPasswd()
	{
		return this.hpcClstrUsrPasswd;
	}

	public void setHpcClstrUsrPasswd(String hpcClstrUsrPasswd)
	{
		this.hpcClstrUsrPasswd = hpcClstrUsrPasswd;
	}

	public String getHpcClstrUsrCrypt()
	{
		return this.hpcClstrUsrCrypt;
	}

	public void setHpcClstrUsrCrypt(String hpcClstrUsrCrypt)
	{
		this.hpcClstrUsrCrypt = hpcClstrUsrCrypt;
	}

	public String getHpcClstrUsrAuto()
	{
		return this.hpcClstrUsrAuto;
	}

	public void setHpcClstrUsrAuto(String hpcClstrUsrAuto)
	{
		this.hpcClstrUsrAuto = hpcClstrUsrAuto;
	}

	public String getHpcClstrUsrIdrsa()
	{
		return this.hpcClstrUsrIdrsa;
	}

	public void setHpcClstrUsrIdrsa(String hpcClstrUsrIdrsa)
	{
		this.hpcClstrUsrIdrsa = hpcClstrUsrIdrsa;
	}

	public BigDecimal getHpcClstrUsrBalance()
	{
		return this.hpcClstrUsrBalance;
	}

	public void setHpcClstrUsrBalance(BigDecimal hpcClstrUsrBalance)
	{
		this.hpcClstrUsrBalance = hpcClstrUsrBalance;
	}

	public BigDecimal getHpcClstrUsrCharged()
	{
		return this.hpcClstrUsrCharged;
	}

	public void setHpcClstrUsrCharged(BigDecimal hpcClstrUsrCharged)
	{
		this.hpcClstrUsrCharged = hpcClstrUsrCharged;
	}

	public BigDecimal getHpcClstrUsrConsumed()
	{
		return this.hpcClstrUsrConsumed;
	}

	public void setHpcClstrUsrConsumed(BigDecimal hpcClstrUsrConsumed)
	{
		this.hpcClstrUsrConsumed = hpcClstrUsrConsumed;
	}

	public BigDecimal getHpcClstrUsrJobFee()
	{
		return this.hpcClstrUsrJobFee;
	}

	public void setHpcClstrUsrJobFee(BigDecimal hpcClstrUsrJobFee)
	{
		this.hpcClstrUsrJobFee = hpcClstrUsrJobFee;
	}

	public Long getHpcClstrUsrJobNum()
	{
		return this.hpcClstrUsrJobNum;
	}

	public void setHpcClstrUsrJobNum(Long hpcClstrUsrJobNum)
	{
		this.hpcClstrUsrJobNum = hpcClstrUsrJobNum;
	}

	public Long getHpcClstrUsrJobHosts()
	{
		return this.hpcClstrUsrJobHosts;
	}

	public void setHpcClstrUsrJobHosts(Long hpcClstrUsrJobHosts)
	{
		this.hpcClstrUsrJobHosts = hpcClstrUsrJobHosts;
	}

	public Long getHpcClstrUsrJobCores()
	{
		return this.hpcClstrUsrJobCores;
	}

	public void setHpcClstrUsrJobCores(Long hpcClstrUsrJobCores)
	{
		this.hpcClstrUsrJobCores = hpcClstrUsrJobCores;
	}

	public Date getHpcClstrUsrJobTime()
	{
		return this.hpcClstrUsrJobTime;
	}

	public void setHpcClstrUsrJobTime(Date hpcClstrUsrJobTime)
	{
		this.hpcClstrUsrJobTime = hpcClstrUsrJobTime;
	}

	public BigDecimal getHpcClstrUsrStrgFee()
	{
		return this.hpcClstrUsrStrgFee;
	}

	public void setHpcClstrUsrStrgFee(BigDecimal hpcClstrUsrStrgFee)
	{
		this.hpcClstrUsrStrgFee = hpcClstrUsrStrgFee;
	}

	public BigDecimal getHpcClstrUsrStrgCap()
	{
		return this.hpcClstrUsrStrgCap;
	}

	public void setHpcClstrUsrStrgCap(BigDecimal hpcClstrUsrStrgCap)
	{
		this.hpcClstrUsrStrgCap = hpcClstrUsrStrgCap;
	}

	public String getHpcClstrUsrStrgUnit()
	{
		return this.hpcClstrUsrStrgUnit;
	}

	public void setHpcClstrUsrStrgUnit(String hpcClstrUsrStrgUnit)
	{
		this.hpcClstrUsrStrgUnit = hpcClstrUsrStrgUnit;
	}

	public Date getHpcClstrUsrStrgTime()
	{
		return this.hpcClstrUsrStrgTime;
	}

	public void setHpcClstrUsrStrgTime(Date hpcClstrUsrStrgTime)
	{
		this.hpcClstrUsrStrgTime = hpcClstrUsrStrgTime;
	}

	public Set getHpcPayments()
	{
		return this.hpcPayments;
	}

	public void setHpcPayments(Set hpcPayments)
	{
		this.hpcPayments = hpcPayments;
	}

	public Set getHpcResLtds()
	{
		return this.hpcResLtds;
	}

	public void setHpcResLtds(Set hpcResLtds)
	{
		this.hpcResLtds = hpcResLtds;
	}

	public Set getHpcJobs()
	{
		return this.hpcJobs;
	}

	public void setHpcJobs(Set hpcJobs)
	{
		this.hpcJobs = hpcJobs;
	}

}
