package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HpcCloudUser generated by hbm2java
 */
public class HpcCloudUser implements java.io.Serializable
{

	private long hpcUserId;
	private HpcCloudUser hpcCloudUser;
	private String hpcUserName;
	private String hpcUserPasswd;
	private BigDecimal hpcUserBalance;
	private BigDecimal hpcUserCharged;
	private BigDecimal hpcUserConsumed;
	private BigDecimal hpcUserJobFee;
	private Long hpcUserJobNum;
	private Long hpcUserJobHosts;
	private Long hpcUserJobCores;
	private Date hpcUserJobTime;
	private BigDecimal hpcUserStorageFee;
	private BigDecimal hpcUserStorageCap;
	private String hpcUserStorageUnit;
	private Date hpcUserStorageTime;
	private Set hpcCloudUsers = new HashSet(0);
	private Set hpcJobsForHpcJobSubmitUser = new HashSet(0);
	private Set hpcGroupAllocs = new HashSet(0);
	private Set hpcJobsForHpcHobPaidUser = new HashSet(0);
	private Set hpcJobPrices = new HashSet(0);
	private Set hpcClusterUsers = new HashSet(0);
	private Set hpcRoleAllocs = new HashSet(0);

	public HpcCloudUser()
	{
	}

	public HpcCloudUser(long hpcUserId, String hpcUserName)
	{
		this.hpcUserId = hpcUserId;
		this.hpcUserName = hpcUserName;
	}

	public HpcCloudUser(long hpcUserId, HpcCloudUser hpcCloudUser, String hpcUserName, String hpcUserPasswd, BigDecimal hpcUserBalance, BigDecimal hpcUserCharged, BigDecimal hpcUserConsumed, BigDecimal hpcUserJobFee, Long hpcUserJobNum, Long hpcUserJobHosts, Long hpcUserJobCores,
			Date hpcUserJobTime, BigDecimal hpcUserStorageFee, BigDecimal hpcUserStorageCap, String hpcUserStorageUnit, Date hpcUserStorageTime, Set hpcCloudUsers, Set hpcJobsForHpcJobSubmitUser, Set hpcGroupAllocs, Set hpcJobsForHpcHobPaidUser, Set hpcJobPrices,
			Set hpcClusterUsers, Set hpcRoleAllocs)
	{
		this.hpcUserId = hpcUserId;
		this.hpcCloudUser = hpcCloudUser;
		this.hpcUserName = hpcUserName;
		this.hpcUserPasswd = hpcUserPasswd;
		this.hpcUserBalance = hpcUserBalance;
		this.hpcUserCharged = hpcUserCharged;
		this.hpcUserConsumed = hpcUserConsumed;
		this.hpcUserJobFee = hpcUserJobFee;
		this.hpcUserJobNum = hpcUserJobNum;
		this.hpcUserJobHosts = hpcUserJobHosts;
		this.hpcUserJobCores = hpcUserJobCores;
		this.hpcUserJobTime = hpcUserJobTime;
		this.hpcUserStorageFee = hpcUserStorageFee;
		this.hpcUserStorageCap = hpcUserStorageCap;
		this.hpcUserStorageUnit = hpcUserStorageUnit;
		this.hpcUserStorageTime = hpcUserStorageTime;
		this.hpcCloudUsers = hpcCloudUsers;
		this.hpcJobsForHpcJobSubmitUser = hpcJobsForHpcJobSubmitUser;
		this.hpcGroupAllocs = hpcGroupAllocs;
		this.hpcJobsForHpcHobPaidUser = hpcJobsForHpcHobPaidUser;
		this.hpcJobPrices = hpcJobPrices;
		this.hpcClusterUsers = hpcClusterUsers;
		this.hpcRoleAllocs = hpcRoleAllocs;
	}

	public long getHpcUserId()
	{
		return this.hpcUserId;
	}

	public void setHpcUserId(long hpcUserId)
	{
		this.hpcUserId = hpcUserId;
	}

	public HpcCloudUser getHpcCloudUser()
	{
		return this.hpcCloudUser;
	}

	public void setHpcCloudUser(HpcCloudUser hpcCloudUser)
	{
		this.hpcCloudUser = hpcCloudUser;
	}

	public String getHpcUserName()
	{
		return this.hpcUserName;
	}

	public void setHpcUserName(String hpcUserName)
	{
		this.hpcUserName = hpcUserName;
	}

	public String getHpcUserPasswd()
	{
		return this.hpcUserPasswd;
	}

	public void setHpcUserPasswd(String hpcUserPasswd)
	{
		this.hpcUserPasswd = hpcUserPasswd;
	}

	public BigDecimal getHpcUserBalance()
	{
		return this.hpcUserBalance;
	}

	public void setHpcUserBalance(BigDecimal hpcUserBalance)
	{
		this.hpcUserBalance = hpcUserBalance;
	}

	public BigDecimal getHpcUserCharged()
	{
		return this.hpcUserCharged;
	}

	public void setHpcUserCharged(BigDecimal hpcUserCharged)
	{
		this.hpcUserCharged = hpcUserCharged;
	}

	public BigDecimal getHpcUserConsumed()
	{
		return this.hpcUserConsumed;
	}

	public void setHpcUserConsumed(BigDecimal hpcUserConsumed)
	{
		this.hpcUserConsumed = hpcUserConsumed;
	}

	public BigDecimal getHpcUserJobFee()
	{
		return this.hpcUserJobFee;
	}

	public void setHpcUserJobFee(BigDecimal hpcUserJobFee)
	{
		this.hpcUserJobFee = hpcUserJobFee;
	}

	public Long getHpcUserJobNum()
	{
		return this.hpcUserJobNum;
	}

	public void setHpcUserJobNum(Long hpcUserJobNum)
	{
		this.hpcUserJobNum = hpcUserJobNum;
	}

	public Long getHpcUserJobHosts()
	{
		return this.hpcUserJobHosts;
	}

	public void setHpcUserJobHosts(Long hpcUserJobHosts)
	{
		this.hpcUserJobHosts = hpcUserJobHosts;
	}

	public Long getHpcUserJobCores()
	{
		return this.hpcUserJobCores;
	}

	public void setHpcUserJobCores(Long hpcUserJobCores)
	{
		this.hpcUserJobCores = hpcUserJobCores;
	}

	public Date getHpcUserJobTime()
	{
		return this.hpcUserJobTime;
	}

	public void setHpcUserJobTime(Date hpcUserJobTime)
	{
		this.hpcUserJobTime = hpcUserJobTime;
	}

	public BigDecimal getHpcUserStorageFee()
	{
		return this.hpcUserStorageFee;
	}

	public void setHpcUserStorageFee(BigDecimal hpcUserStorageFee)
	{
		this.hpcUserStorageFee = hpcUserStorageFee;
	}

	public BigDecimal getHpcUserStorageCap()
	{
		return this.hpcUserStorageCap;
	}

	public void setHpcUserStorageCap(BigDecimal hpcUserStorageCap)
	{
		this.hpcUserStorageCap = hpcUserStorageCap;
	}

	public String getHpcUserStorageUnit()
	{
		return this.hpcUserStorageUnit;
	}

	public void setHpcUserStorageUnit(String hpcUserStorageUnit)
	{
		this.hpcUserStorageUnit = hpcUserStorageUnit;
	}

	public Date getHpcUserStorageTime()
	{
		return this.hpcUserStorageTime;
	}

	public void setHpcUserStorageTime(Date hpcUserStorageTime)
	{
		this.hpcUserStorageTime = hpcUserStorageTime;
	}

	public Set getHpcCloudUsers()
	{
		return this.hpcCloudUsers;
	}

	public void setHpcCloudUsers(Set hpcCloudUsers)
	{
		this.hpcCloudUsers = hpcCloudUsers;
	}

	public Set getHpcJobsForHpcJobSubmitUser()
	{
		return this.hpcJobsForHpcJobSubmitUser;
	}

	public void setHpcJobsForHpcJobSubmitUser(Set hpcJobsForHpcJobSubmitUser)
	{
		this.hpcJobsForHpcJobSubmitUser = hpcJobsForHpcJobSubmitUser;
	}

	public Set getHpcGroupAllocs()
	{
		return this.hpcGroupAllocs;
	}

	public void setHpcGroupAllocs(Set hpcGroupAllocs)
	{
		this.hpcGroupAllocs = hpcGroupAllocs;
	}

	public Set getHpcJobsForHpcHobPaidUser()
	{
		return this.hpcJobsForHpcHobPaidUser;
	}

	public void setHpcJobsForHpcHobPaidUser(Set hpcJobsForHpcHobPaidUser)
	{
		this.hpcJobsForHpcHobPaidUser = hpcJobsForHpcHobPaidUser;
	}

	public Set getHpcJobPrices()
	{
		return this.hpcJobPrices;
	}

	public void setHpcJobPrices(Set hpcJobPrices)
	{
		this.hpcJobPrices = hpcJobPrices;
	}

	public Set getHpcClusterUsers()
	{
		return this.hpcClusterUsers;
	}

	public void setHpcClusterUsers(Set hpcClusterUsers)
	{
		this.hpcClusterUsers = hpcClusterUsers;
	}

	public Set getHpcRoleAllocs()
	{
		return this.hpcRoleAllocs;
	}

	public void setHpcRoleAllocs(Set hpcRoleAllocs)
	{
		this.hpcRoleAllocs = hpcRoleAllocs;
	}

}
