package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

/**
 * HpcGroupAlloc generated by hbm2java
 */
public class HpcGroupAlloc implements java.io.Serializable
{

	private Long hpcGroupAllocId;
	private HpcCloudUser hpcCloudUser;
	private HpcGroup hpcGroup;

	public HpcGroupAlloc()
	{
	}

	public HpcGroupAlloc(HpcCloudUser hpcCloudUser, HpcGroup hpcGroup)
	{
		this.hpcCloudUser = hpcCloudUser;
		this.hpcGroup = hpcGroup;
	}

	public Long getHpcGroupAllocId()
	{
		return this.hpcGroupAllocId;
	}

	public void setHpcGroupAllocId(Long hpcGroupAllocId)
	{
		this.hpcGroupAllocId = hpcGroupAllocId;
	}

	public HpcCloudUser getHpcCloudUser()
	{
		return this.hpcCloudUser;
	}

	public void setHpcCloudUser(HpcCloudUser hpcCloudUser)
	{
		this.hpcCloudUser = hpcCloudUser;
	}

	public HpcGroup getHpcGroup()
	{
		return this.hpcGroup;
	}

	public void setHpcGroup(HpcGroup hpcGroup)
	{
		this.hpcGroup = hpcGroup;
	}

}
