package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * HpcGroup generated by hbm2java
 */
public class HpcGroup implements java.io.Serializable
{

	private Long hpcGroupId;
	private HpcGroup hpcGroup;
	private String hpcGroupName;
	private String hpcGroupCode;
	private String hpcGroupDesc;
	private Set hpcGroupAllocs = new HashSet(0);
	private Set hpcGroups = new HashSet(0);
	private Set hpcJobPrices = new HashSet(0);

	public HpcGroup()
	{
	}

	public HpcGroup(String hpcGroupName)
	{
		this.hpcGroupName = hpcGroupName;
	}

	public HpcGroup(HpcGroup hpcGroup, String hpcGroupName, String hpcGroupCode, String hpcGroupDesc, Set hpcGroupAllocs, Set hpcGroups, Set hpcJobPrices)
	{
		this.hpcGroup = hpcGroup;
		this.hpcGroupName = hpcGroupName;
		this.hpcGroupCode = hpcGroupCode;
		this.hpcGroupDesc = hpcGroupDesc;
		this.hpcGroupAllocs = hpcGroupAllocs;
		this.hpcGroups = hpcGroups;
		this.hpcJobPrices = hpcJobPrices;
	}

	public Long getHpcGroupId()
	{
		return this.hpcGroupId;
	}

	public void setHpcGroupId(Long hpcGroupId)
	{
		this.hpcGroupId = hpcGroupId;
	}

	public HpcGroup getHpcGroup()
	{
		return this.hpcGroup;
	}

	public void setHpcGroup(HpcGroup hpcGroup)
	{
		this.hpcGroup = hpcGroup;
	}

	public String getHpcGroupName()
	{
		return this.hpcGroupName;
	}

	public void setHpcGroupName(String hpcGroupName)
	{
		this.hpcGroupName = hpcGroupName;
	}

	public String getHpcGroupCode()
	{
		return this.hpcGroupCode;
	}

	public void setHpcGroupCode(String hpcGroupCode)
	{
		this.hpcGroupCode = hpcGroupCode;
	}

	public String getHpcGroupDesc()
	{
		return this.hpcGroupDesc;
	}

	public void setHpcGroupDesc(String hpcGroupDesc)
	{
		this.hpcGroupDesc = hpcGroupDesc;
	}

	public Set getHpcGroupAllocs()
	{
		return this.hpcGroupAllocs;
	}

	public void setHpcGroupAllocs(Set hpcGroupAllocs)
	{
		this.hpcGroupAllocs = hpcGroupAllocs;
	}

	public Set getHpcGroups()
	{
		return this.hpcGroups;
	}

	public void setHpcGroups(Set hpcGroups)
	{
		this.hpcGroups = hpcGroups;
	}

	public Set getHpcJobPrices()
	{
		return this.hpcJobPrices;
	}

	public void setHpcJobPrices(Set hpcJobPrices)
	{
		this.hpcJobPrices = hpcJobPrices;
	}

}
