package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

/**
 * HpcInterface generated by hbm2java
 */
public class HpcInterface implements java.io.Serializable
{

	private Long hpcIfcId;
	private HpcNode hpcNode;
	private String hpcIfcName;
	private String hpcIfcAddr;
	private String hpcIfcAlias;

	public HpcInterface()
	{
	}

	public HpcInterface(String hpcIfcName, String hpcIfcAddr, String hpcIfcAlias)
	{
		this.hpcIfcName = hpcIfcName;
		this.hpcIfcAddr = hpcIfcAddr;
		this.hpcIfcAlias = hpcIfcAlias;
	}

	public HpcInterface(HpcNode hpcNode, String hpcIfcName, String hpcIfcAddr, String hpcIfcAlias)
	{
		this.hpcNode = hpcNode;
		this.hpcIfcName = hpcIfcName;
		this.hpcIfcAddr = hpcIfcAddr;
		this.hpcIfcAlias = hpcIfcAlias;
	}

	public Long getHpcIfcId()
	{
		return this.hpcIfcId;
	}

	public void setHpcIfcId(Long hpcIfcId)
	{
		this.hpcIfcId = hpcIfcId;
	}

	public HpcNode getHpcNode()
	{
		return this.hpcNode;
	}

	public void setHpcNode(HpcNode hpcNode)
	{
		this.hpcNode = hpcNode;
	}

	public String getHpcIfcName()
	{
		return this.hpcIfcName;
	}

	public void setHpcIfcName(String hpcIfcName)
	{
		this.hpcIfcName = hpcIfcName;
	}

	public String getHpcIfcAddr()
	{
		return this.hpcIfcAddr;
	}

	public void setHpcIfcAddr(String hpcIfcAddr)
	{
		this.hpcIfcAddr = hpcIfcAddr;
	}

	public String getHpcIfcAlias()
	{
		return this.hpcIfcAlias;
	}

	public void setHpcIfcAlias(String hpcIfcAlias)
	{
		this.hpcIfcAlias = hpcIfcAlias;
	}

}
