package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * HpcJobPrice generated by hbm2java
 */
public class HpcJobPrice implements java.io.Serializable
{

	private Long hpcJobPriceId;
	private HpcApp hpcApp;
	private HpcCloudUser hpcCloudUser;
	private HpcCluster hpcCluster;
	private HpcGroup hpcGroup;
	private BigDecimal hpcJobPriceValue;
	private Set hpcJobs = new HashSet(0);

	public HpcJobPrice()
	{
	}

	public HpcJobPrice(BigDecimal hpcJobPriceValue)
	{
		this.hpcJobPriceValue = hpcJobPriceValue;
	}

	public HpcJobPrice(HpcApp hpcApp, HpcCloudUser hpcCloudUser, HpcCluster hpcCluster, HpcGroup hpcGroup, BigDecimal hpcJobPriceValue, Set hpcJobs)
	{
		this.hpcApp = hpcApp;
		this.hpcCloudUser = hpcCloudUser;
		this.hpcCluster = hpcCluster;
		this.hpcGroup = hpcGroup;
		this.hpcJobPriceValue = hpcJobPriceValue;
		this.hpcJobs = hpcJobs;
	}

	public Long getHpcJobPriceId()
	{
		return this.hpcJobPriceId;
	}

	public void setHpcJobPriceId(Long hpcJobPriceId)
	{
		this.hpcJobPriceId = hpcJobPriceId;
	}

	public HpcApp getHpcApp()
	{
		return this.hpcApp;
	}

	public void setHpcApp(HpcApp hpcApp)
	{
		this.hpcApp = hpcApp;
	}

	public HpcCloudUser getHpcCloudUser()
	{
		return this.hpcCloudUser;
	}

	public void setHpcCloudUser(HpcCloudUser hpcCloudUser)
	{
		this.hpcCloudUser = hpcCloudUser;
	}

	public HpcCluster getHpcCluster()
	{
		return this.hpcCluster;
	}

	public void setHpcCluster(HpcCluster hpcCluster)
	{
		this.hpcCluster = hpcCluster;
	}

	public HpcGroup getHpcGroup()
	{
		return this.hpcGroup;
	}

	public void setHpcGroup(HpcGroup hpcGroup)
	{
		this.hpcGroup = hpcGroup;
	}

	public BigDecimal getHpcJobPriceValue()
	{
		return this.hpcJobPriceValue;
	}

	public void setHpcJobPriceValue(BigDecimal hpcJobPriceValue)
	{
		this.hpcJobPriceValue = hpcJobPriceValue;
	}

	public Set getHpcJobs()
	{
		return this.hpcJobs;
	}

	public void setHpcJobs(Set hpcJobs)
	{
		this.hpcJobs = hpcJobs;
	}

}
