package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * HpcParameter generated by hbm2java
 */
public class HpcParameter implements java.io.Serializable
{

	private Long hpcParamId;
	private String hpcParamName;
	private String hpcParamDesc;
	private Set hpcParamAssigns = new HashSet(0);

	public HpcParameter()
	{
	}

	public HpcParameter(String hpcParamName)
	{
		this.hpcParamName = hpcParamName;
	}

	public HpcParameter(String hpcParamName, String hpcParamDesc, Set hpcParamAssigns)
	{
		this.hpcParamName = hpcParamName;
		this.hpcParamDesc = hpcParamDesc;
		this.hpcParamAssigns = hpcParamAssigns;
	}

	public Long getHpcParamId()
	{
		return this.hpcParamId;
	}

	public void setHpcParamId(Long hpcParamId)
	{
		this.hpcParamId = hpcParamId;
	}

	public String getHpcParamName()
	{
		return this.hpcParamName;
	}

	public void setHpcParamName(String hpcParamName)
	{
		this.hpcParamName = hpcParamName;
	}

	public String getHpcParamDesc()
	{
		return this.hpcParamDesc;
	}

	public void setHpcParamDesc(String hpcParamDesc)
	{
		this.hpcParamDesc = hpcParamDesc;
	}

	public Set getHpcParamAssigns()
	{
		return this.hpcParamAssigns;
	}

	public void setHpcParamAssigns(Set hpcParamAssigns)
	{
		this.hpcParamAssigns = hpcParamAssigns;
	}

}
