package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * HpcProperty generated by hbm2java
 */
public class HpcProperty implements java.io.Serializable
{

	private Long hpcPropId;
	private String hpcPropName;
	private String hpcPropDesc;
	private Set hpcPropertyAssigns = new HashSet(0);

	public HpcProperty()
	{
	}

	public HpcProperty(String hpcPropName)
	{
		this.hpcPropName = hpcPropName;
	}

	public HpcProperty(String hpcPropName, String hpcPropDesc, Set hpcPropertyAssigns)
	{
		this.hpcPropName = hpcPropName;
		this.hpcPropDesc = hpcPropDesc;
		this.hpcPropertyAssigns = hpcPropertyAssigns;
	}

	public Long getHpcPropId()
	{
		return this.hpcPropId;
	}

	public void setHpcPropId(Long hpcPropId)
	{
		this.hpcPropId = hpcPropId;
	}

	public String getHpcPropName()
	{
		return this.hpcPropName;
	}

	public void setHpcPropName(String hpcPropName)
	{
		this.hpcPropName = hpcPropName;
	}

	public String getHpcPropDesc()
	{
		return this.hpcPropDesc;
	}

	public void setHpcPropDesc(String hpcPropDesc)
	{
		this.hpcPropDesc = hpcPropDesc;
	}

	public Set getHpcPropertyAssigns()
	{
		return this.hpcPropertyAssigns;
	}

	public void setHpcPropertyAssigns(Set hpcPropertyAssigns)
	{
		this.hpcPropertyAssigns = hpcPropertyAssigns;
	}

}
