package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * HpcPropertyAssign generated by hbm2java
 */
public class HpcPropertyAssign implements java.io.Serializable
{

	private Long hpcPropertyAssignId;
	private HpcNode hpcNode;
	private HpcProperty hpcProperty;
	private String hpcPropertyAssignValue;
	private Date hpcPropertyAssignTime;

	public HpcPropertyAssign()
	{
	}

	public HpcPropertyAssign(String hpcPropertyAssignValue, Date hpcPropertyAssignTime)
	{
		this.hpcPropertyAssignValue = hpcPropertyAssignValue;
		this.hpcPropertyAssignTime = hpcPropertyAssignTime;
	}

	public HpcPropertyAssign(HpcNode hpcNode, HpcProperty hpcProperty, String hpcPropertyAssignValue, Date hpcPropertyAssignTime)
	{
		this.hpcNode = hpcNode;
		this.hpcProperty = hpcProperty;
		this.hpcPropertyAssignValue = hpcPropertyAssignValue;
		this.hpcPropertyAssignTime = hpcPropertyAssignTime;
	}

	public Long getHpcPropertyAssignId()
	{
		return this.hpcPropertyAssignId;
	}

	public void setHpcPropertyAssignId(Long hpcPropertyAssignId)
	{
		this.hpcPropertyAssignId = hpcPropertyAssignId;
	}

	public HpcNode getHpcNode()
	{
		return this.hpcNode;
	}

	public void setHpcNode(HpcNode hpcNode)
	{
		this.hpcNode = hpcNode;
	}

	public HpcProperty getHpcProperty()
	{
		return this.hpcProperty;
	}

	public void setHpcProperty(HpcProperty hpcProperty)
	{
		this.hpcProperty = hpcProperty;
	}

	public String getHpcPropertyAssignValue()
	{
		return this.hpcPropertyAssignValue;
	}

	public void setHpcPropertyAssignValue(String hpcPropertyAssignValue)
	{
		this.hpcPropertyAssignValue = hpcPropertyAssignValue;
	}

	public Date getHpcPropertyAssignTime()
	{
		return this.hpcPropertyAssignTime;
	}

	public void setHpcPropertyAssignTime(Date hpcPropertyAssignTime)
	{
		this.hpcPropertyAssignTime = hpcPropertyAssignTime;
	}

}
