package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * HpcRm generated by hbm2java
 */
public class HpcRm implements java.io.Serializable
{

	private Long hpcRmId;
	private HpcCluster hpcCluster;
	private HpcNode hpcNodeByHpcRmControll;
	private HpcNode hpcNodeByHpcRmAccount;
	private HpcNode hpcNodeByHcRmInstall;
	private HpcNode hpcNodeByHpcRmStorage;
	private HpcNode hpcNodeByHpcRmSchedule;
	private String hpcRmName;
	private String hpcRmVersion;
	private String hpcRmTopdir;
	private String hpcRmBin;
	private String hpcRmSbin;
	private String hpcRmLib;
	private String hpcRmEtc;
	private Set hpcClusters = new HashSet(0);

	public HpcRm()
	{
	}

	public HpcRm(String hpcRmName, String hpcRmVersion, String hpcRmTopdir)
	{
		this.hpcRmName = hpcRmName;
		this.hpcRmVersion = hpcRmVersion;
		this.hpcRmTopdir = hpcRmTopdir;
	}

	public HpcRm(HpcCluster hpcCluster, HpcNode hpcNodeByHpcRmControll, HpcNode hpcNodeByHpcRmAccount, HpcNode hpcNodeByHcRmInstall, HpcNode hpcNodeByHpcRmStorage, HpcNode hpcNodeByHpcRmSchedule, String hpcRmName, String hpcRmVersion, String hpcRmTopdir, String hpcRmBin,
			String hpcRmSbin, String hpcRmLib, String hpcRmEtc, Set hpcClusters)
	{
		this.hpcCluster = hpcCluster;
		this.hpcNodeByHpcRmControll = hpcNodeByHpcRmControll;
		this.hpcNodeByHpcRmAccount = hpcNodeByHpcRmAccount;
		this.hpcNodeByHcRmInstall = hpcNodeByHcRmInstall;
		this.hpcNodeByHpcRmStorage = hpcNodeByHpcRmStorage;
		this.hpcNodeByHpcRmSchedule = hpcNodeByHpcRmSchedule;
		this.hpcRmName = hpcRmName;
		this.hpcRmVersion = hpcRmVersion;
		this.hpcRmTopdir = hpcRmTopdir;
		this.hpcRmBin = hpcRmBin;
		this.hpcRmSbin = hpcRmSbin;
		this.hpcRmLib = hpcRmLib;
		this.hpcRmEtc = hpcRmEtc;
		this.hpcClusters = hpcClusters;
	}

	public Long getHpcRmId()
	{
		return this.hpcRmId;
	}

	public void setHpcRmId(Long hpcRmId)
	{
		this.hpcRmId = hpcRmId;
	}

	public HpcCluster getHpcCluster()
	{
		return this.hpcCluster;
	}

	public void setHpcCluster(HpcCluster hpcCluster)
	{
		this.hpcCluster = hpcCluster;
	}

	public HpcNode getHpcNodeByHpcRmControll()
	{
		return this.hpcNodeByHpcRmControll;
	}

	public void setHpcNodeByHpcRmControll(HpcNode hpcNodeByHpcRmControll)
	{
		this.hpcNodeByHpcRmControll = hpcNodeByHpcRmControll;
	}

	public HpcNode getHpcNodeByHpcRmAccount()
	{
		return this.hpcNodeByHpcRmAccount;
	}

	public void setHpcNodeByHpcRmAccount(HpcNode hpcNodeByHpcRmAccount)
	{
		this.hpcNodeByHpcRmAccount = hpcNodeByHpcRmAccount;
	}

	public HpcNode getHpcNodeByHcRmInstall()
	{
		return this.hpcNodeByHcRmInstall;
	}

	public void setHpcNodeByHcRmInstall(HpcNode hpcNodeByHcRmInstall)
	{
		this.hpcNodeByHcRmInstall = hpcNodeByHcRmInstall;
	}

	public HpcNode getHpcNodeByHpcRmStorage()
	{
		return this.hpcNodeByHpcRmStorage;
	}

	public void setHpcNodeByHpcRmStorage(HpcNode hpcNodeByHpcRmStorage)
	{
		this.hpcNodeByHpcRmStorage = hpcNodeByHpcRmStorage;
	}

	public HpcNode getHpcNodeByHpcRmSchedule()
	{
		return this.hpcNodeByHpcRmSchedule;
	}

	public void setHpcNodeByHpcRmSchedule(HpcNode hpcNodeByHpcRmSchedule)
	{
		this.hpcNodeByHpcRmSchedule = hpcNodeByHpcRmSchedule;
	}

	public String getHpcRmName()
	{
		return this.hpcRmName;
	}

	public void setHpcRmName(String hpcRmName)
	{
		this.hpcRmName = hpcRmName;
	}

	public String getHpcRmVersion()
	{
		return this.hpcRmVersion;
	}

	public void setHpcRmVersion(String hpcRmVersion)
	{
		this.hpcRmVersion = hpcRmVersion;
	}

	public String getHpcRmTopdir()
	{
		return this.hpcRmTopdir;
	}

	public void setHpcRmTopdir(String hpcRmTopdir)
	{
		this.hpcRmTopdir = hpcRmTopdir;
	}

	public String getHpcRmBin()
	{
		return this.hpcRmBin;
	}

	public void setHpcRmBin(String hpcRmBin)
	{
		this.hpcRmBin = hpcRmBin;
	}

	public String getHpcRmSbin()
	{
		return this.hpcRmSbin;
	}

	public void setHpcRmSbin(String hpcRmSbin)
	{
		this.hpcRmSbin = hpcRmSbin;
	}

	public String getHpcRmLib()
	{
		return this.hpcRmLib;
	}

	public void setHpcRmLib(String hpcRmLib)
	{
		this.hpcRmLib = hpcRmLib;
	}

	public String getHpcRmEtc()
	{
		return this.hpcRmEtc;
	}

	public void setHpcRmEtc(String hpcRmEtc)
	{
		this.hpcRmEtc = hpcRmEtc;
	}

	public Set getHpcClusters()
	{
		return this.hpcClusters;
	}

	public void setHpcClusters(Set hpcClusters)
	{
		this.hpcClusters = hpcClusters;
	}

}
