package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * HpcRole generated by hbm2java
 */
public class HpcRole implements java.io.Serializable
{

	private Long hpcRoleId;
	private String hpcRoleName;
	private int hpcRoleCode;
	private String hpcRoleDescription;
	private String hpcRoleRights;
	private String hpcRoleTemplate;
	private Set hpcRoleAllocs = new HashSet(0);

	public HpcRole()
	{
	}

	public HpcRole(String hpcRoleName, int hpcRoleCode)
	{
		this.hpcRoleName = hpcRoleName;
		this.hpcRoleCode = hpcRoleCode;
	}

	public HpcRole(String hpcRoleName, int hpcRoleCode, String hpcRoleDescription, String hpcRoleRights, String hpcRoleTemplate, Set hpcRoleAllocs)
	{
		this.hpcRoleName = hpcRoleName;
		this.hpcRoleCode = hpcRoleCode;
		this.hpcRoleDescription = hpcRoleDescription;
		this.hpcRoleRights = hpcRoleRights;
		this.hpcRoleTemplate = hpcRoleTemplate;
		this.hpcRoleAllocs = hpcRoleAllocs;
	}

	public Long getHpcRoleId()
	{
		return this.hpcRoleId;
	}

	public void setHpcRoleId(Long hpcRoleId)
	{
		this.hpcRoleId = hpcRoleId;
	}

	public String getHpcRoleName()
	{
		return this.hpcRoleName;
	}

	public void setHpcRoleName(String hpcRoleName)
	{
		this.hpcRoleName = hpcRoleName;
	}

	public int getHpcRoleCode()
	{
		return this.hpcRoleCode;
	}

	public void setHpcRoleCode(int hpcRoleCode)
	{
		this.hpcRoleCode = hpcRoleCode;
	}

	public String getHpcRoleDescription()
	{
		return this.hpcRoleDescription;
	}

	public void setHpcRoleDescription(String hpcRoleDescription)
	{
		this.hpcRoleDescription = hpcRoleDescription;
	}

	public String getHpcRoleRights()
	{
		return this.hpcRoleRights;
	}

	public void setHpcRoleRights(String hpcRoleRights)
	{
		this.hpcRoleRights = hpcRoleRights;
	}

	public String getHpcRoleTemplate()
	{
		return this.hpcRoleTemplate;
	}

	public void setHpcRoleTemplate(String hpcRoleTemplate)
	{
		this.hpcRoleTemplate = hpcRoleTemplate;
	}

	public Set getHpcRoleAllocs()
	{
		return this.hpcRoleAllocs;
	}

	public void setHpcRoleAllocs(Set hpcRoleAllocs)
	{
		this.hpcRoleAllocs = hpcRoleAllocs;
	}

}
