package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

/**
 * HpcResLtd generated by hbm2java
 */
public class HpcResLtd implements java.io.Serializable
{

	private Long hpcResLtdId;
	private HpcClusterUser hpcClusterUser;
	private HpcResource hpcResource;
	private long hpcResLtdNum;
	private String hpcResLtdUnit;

	public HpcResLtd()
	{
	}

	public HpcResLtd(long hpcResLtdNum, String hpcResLtdUnit)
	{
		this.hpcResLtdNum = hpcResLtdNum;
		this.hpcResLtdUnit = hpcResLtdUnit;
	}

	public HpcResLtd(HpcClusterUser hpcClusterUser, HpcResource hpcResource, long hpcResLtdNum, String hpcResLtdUnit)
	{
		this.hpcClusterUser = hpcClusterUser;
		this.hpcResource = hpcResource;
		this.hpcResLtdNum = hpcResLtdNum;
		this.hpcResLtdUnit = hpcResLtdUnit;
	}

	public Long getHpcResLtdId()
	{
		return this.hpcResLtdId;
	}

	public void setHpcResLtdId(Long hpcResLtdId)
	{
		this.hpcResLtdId = hpcResLtdId;
	}

	public HpcClusterUser getHpcClusterUser()
	{
		return this.hpcClusterUser;
	}

	public void setHpcClusterUser(HpcClusterUser hpcClusterUser)
	{
		this.hpcClusterUser = hpcClusterUser;
	}

	public HpcResource getHpcResource()
	{
		return this.hpcResource;
	}

	public void setHpcResource(HpcResource hpcResource)
	{
		this.hpcResource = hpcResource;
	}

	public long getHpcResLtdNum()
	{
		return this.hpcResLtdNum;
	}

	public void setHpcResLtdNum(long hpcResLtdNum)
	{
		this.hpcResLtdNum = hpcResLtdNum;
	}

	public String getHpcResLtdUnit()
	{
		return this.hpcResLtdUnit;
	}

	public void setHpcResLtdUnit(String hpcResLtdUnit)
	{
		this.hpcResLtdUnit = hpcResLtdUnit;
	}

}
