package hpcgateway.wp.orm.hibernate.mapping;
// Generated Aug 27, 2018 1:18:52 AM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * HpcResource generated by hbm2java
 */
public class HpcResource implements java.io.Serializable
{

	private Long hpcResourceId;
	private HpcCluster hpcCluster;
	private String hpcResourceType;
	private String hpcResourceUnit;
	private String hpcResourceLimit;
	private Set hpcResLtds = new HashSet(0);

	public HpcResource()
	{
	}

	public HpcResource(String hpcResourceType, String hpcResourceUnit, String hpcResourceLimit)
	{
		this.hpcResourceType = hpcResourceType;
		this.hpcResourceUnit = hpcResourceUnit;
		this.hpcResourceLimit = hpcResourceLimit;
	}

	public HpcResource(HpcCluster hpcCluster, String hpcResourceType, String hpcResourceUnit, String hpcResourceLimit, Set hpcResLtds)
	{
		this.hpcCluster = hpcCluster;
		this.hpcResourceType = hpcResourceType;
		this.hpcResourceUnit = hpcResourceUnit;
		this.hpcResourceLimit = hpcResourceLimit;
		this.hpcResLtds = hpcResLtds;
	}

	public Long getHpcResourceId()
	{
		return this.hpcResourceId;
	}

	public void setHpcResourceId(Long hpcResourceId)
	{
		this.hpcResourceId = hpcResourceId;
	}

	public HpcCluster getHpcCluster()
	{
		return this.hpcCluster;
	}

	public void setHpcCluster(HpcCluster hpcCluster)
	{
		this.hpcCluster = hpcCluster;
	}

	public String getHpcResourceType()
	{
		return this.hpcResourceType;
	}

	public void setHpcResourceType(String hpcResourceType)
	{
		this.hpcResourceType = hpcResourceType;
	}

	public String getHpcResourceUnit()
	{
		return this.hpcResourceUnit;
	}

	public void setHpcResourceUnit(String hpcResourceUnit)
	{
		this.hpcResourceUnit = hpcResourceUnit;
	}

	public String getHpcResourceLimit()
	{
		return this.hpcResourceLimit;
	}

	public void setHpcResourceLimit(String hpcResourceLimit)
	{
		this.hpcResourceLimit = hpcResourceLimit;
	}

	public Set getHpcResLtds()
	{
		return this.hpcResLtds;
	}

	public void setHpcResLtds(Set hpcResLtds)
	{
		this.hpcResLtds = hpcResLtds;
	}

}
