package hpcgateway.wp.apps.materials.mappers;

import hpcgateway.wp.apps.materials.beans.HgAppVaspIncar;

public interface HgAppVaspIncarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HG_APP_VASP_INCAR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    int deleteByPrimaryKey(Integer INCAR_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HG_APP_VASP_INCAR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    int insert(HgAppVaspIncar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HG_APP_VASP_INCAR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    int insertSelective(HgAppVaspIncar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HG_APP_VASP_INCAR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    HgAppVaspIncar selectByPrimaryKey(Integer INCAR_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HG_APP_VASP_INCAR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    int updateByPrimaryKeySelective(HgAppVaspIncar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HG_APP_VASP_INCAR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    int updateByPrimaryKey(HgAppVaspIncar record);
}