package hpcgateway.wp.apps.materials.beans;

import java.util.Date;

public class HgAppVaspIncar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.INCAR_ID
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer INCAR_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.JOB_ID
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer JOB_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.NGX
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Double NGX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.NGY
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Double NGY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.NGZ
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Double NGZ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.NGXF
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Double NGXF;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.NGYF
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Double NGYF;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.NGZF
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Double NGZF;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.NBANDS
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer NBANDS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.NBLK
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer NBLK;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.SYSTEM
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private String SYSTEM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.NWRITE
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer NWRITE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.ISTART
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer ISTART;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.ISPIN
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer ISPIN;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.MAGMON
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Date MAGMON;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.INIWAV
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer INIWAV;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.ENCUT
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Float ENCUT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.PREC
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private String PREC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.NELM
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer NELM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.NELMIN
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer NELMIN;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.MELMDL
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer MELMDL;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.EDIFF
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Float EDIFF;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.EDIFFG
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Float EDIFFG;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.NSW
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer NSW;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.NBLOCK
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer NBLOCK;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.KBLOCK
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer KBLOCK;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.IBRION
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer IBRION;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.ISIF
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer ISIF;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.IWAVPR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer IWAVPR;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.ISYM
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer ISYM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.SYMPEREC
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer SYMPEREC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.LCORR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private String LCORR;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.POTIM
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Float POTIM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.TEBEG
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Float TEBEG;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.TEEND
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Float TEEND;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.SMASS
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer SMASS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.NPACO
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer NPACO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.APACO
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer APACO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.POMASS
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Float POMASS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.ZVAL
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Float ZVAL;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.RWIGS
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Date RWIGS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.NELECT
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Float NELECT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.NUPDOWN
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer NUPDOWN;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.EMIN
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Float EMIN;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.EMAX
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Float EMAX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.ISMEAR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer ISMEAR;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.SIGMA
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Float SIGMA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.ALGO
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private String ALGO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.IALGO
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer IALGO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.LREAL
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private String LREAL;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.ROPT
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Date ROPT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.GGA
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private String GGA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.VOSKOWN
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer VOSKOWN;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.DIPOL
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Date DIPOL;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.AMIX
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Float AMIX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.BMIX
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Float BMIX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.WEIMIN
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Float WEIMIN;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.EBREAK
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Float EBREAK;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.DEPER
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Float DEPER;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.TIME
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Float TIME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.LWAVE
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private String LWAVE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.LCHARG
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private String LCHARG;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.LVTOT
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private String LVTOT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.LVHAR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private String LVHAR;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.LELF
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private String LELF;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.LORBIT
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private String LORBIT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.NPAR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private Integer NPAR;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.LSCALAPACK
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private String LSCALAPACK;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.LSCALU
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private String LSCALU;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HG_APP_VASP_INCAR.LASYNC
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    private String LASYNC;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.INCAR_ID
     *
     * @return the value of HG_APP_VASP_INCAR.INCAR_ID
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getINCAR_ID() {
        return INCAR_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.INCAR_ID
     *
     * @param INCAR_ID the value for HG_APP_VASP_INCAR.INCAR_ID
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setINCAR_ID(Integer INCAR_ID) {
        this.INCAR_ID = INCAR_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.JOB_ID
     *
     * @return the value of HG_APP_VASP_INCAR.JOB_ID
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getJOB_ID() {
        return JOB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.JOB_ID
     *
     * @param JOB_ID the value for HG_APP_VASP_INCAR.JOB_ID
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setJOB_ID(Integer JOB_ID) {
        this.JOB_ID = JOB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.NGX
     *
     * @return the value of HG_APP_VASP_INCAR.NGX
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Double getNGX() {
        return NGX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.NGX
     *
     * @param NGX the value for HG_APP_VASP_INCAR.NGX
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setNGX(Double NGX) {
        this.NGX = NGX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.NGY
     *
     * @return the value of HG_APP_VASP_INCAR.NGY
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Double getNGY() {
        return NGY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.NGY
     *
     * @param NGY the value for HG_APP_VASP_INCAR.NGY
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setNGY(Double NGY) {
        this.NGY = NGY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.NGZ
     *
     * @return the value of HG_APP_VASP_INCAR.NGZ
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Double getNGZ() {
        return NGZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.NGZ
     *
     * @param NGZ the value for HG_APP_VASP_INCAR.NGZ
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setNGZ(Double NGZ) {
        this.NGZ = NGZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.NGXF
     *
     * @return the value of HG_APP_VASP_INCAR.NGXF
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Double getNGXF() {
        return NGXF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.NGXF
     *
     * @param NGXF the value for HG_APP_VASP_INCAR.NGXF
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setNGXF(Double NGXF) {
        this.NGXF = NGXF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.NGYF
     *
     * @return the value of HG_APP_VASP_INCAR.NGYF
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Double getNGYF() {
        return NGYF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.NGYF
     *
     * @param NGYF the value for HG_APP_VASP_INCAR.NGYF
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setNGYF(Double NGYF) {
        this.NGYF = NGYF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.NGZF
     *
     * @return the value of HG_APP_VASP_INCAR.NGZF
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Double getNGZF() {
        return NGZF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.NGZF
     *
     * @param NGZF the value for HG_APP_VASP_INCAR.NGZF
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setNGZF(Double NGZF) {
        this.NGZF = NGZF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.NBANDS
     *
     * @return the value of HG_APP_VASP_INCAR.NBANDS
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getNBANDS() {
        return NBANDS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.NBANDS
     *
     * @param NBANDS the value for HG_APP_VASP_INCAR.NBANDS
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setNBANDS(Integer NBANDS) {
        this.NBANDS = NBANDS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.NBLK
     *
     * @return the value of HG_APP_VASP_INCAR.NBLK
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getNBLK() {
        return NBLK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.NBLK
     *
     * @param NBLK the value for HG_APP_VASP_INCAR.NBLK
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setNBLK(Integer NBLK) {
        this.NBLK = NBLK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.SYSTEM
     *
     * @return the value of HG_APP_VASP_INCAR.SYSTEM
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public String getSYSTEM() {
        return SYSTEM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.SYSTEM
     *
     * @param SYSTEM the value for HG_APP_VASP_INCAR.SYSTEM
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setSYSTEM(String SYSTEM) {
        this.SYSTEM = SYSTEM == null ? null : SYSTEM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.NWRITE
     *
     * @return the value of HG_APP_VASP_INCAR.NWRITE
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getNWRITE() {
        return NWRITE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.NWRITE
     *
     * @param NWRITE the value for HG_APP_VASP_INCAR.NWRITE
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setNWRITE(Integer NWRITE) {
        this.NWRITE = NWRITE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.ISTART
     *
     * @return the value of HG_APP_VASP_INCAR.ISTART
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getISTART() {
        return ISTART;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.ISTART
     *
     * @param ISTART the value for HG_APP_VASP_INCAR.ISTART
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setISTART(Integer ISTART) {
        this.ISTART = ISTART;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.ISPIN
     *
     * @return the value of HG_APP_VASP_INCAR.ISPIN
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getISPIN() {
        return ISPIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.ISPIN
     *
     * @param ISPIN the value for HG_APP_VASP_INCAR.ISPIN
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setISPIN(Integer ISPIN) {
        this.ISPIN = ISPIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.MAGMON
     *
     * @return the value of HG_APP_VASP_INCAR.MAGMON
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Date getMAGMON() {
        return MAGMON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.MAGMON
     *
     * @param MAGMON the value for HG_APP_VASP_INCAR.MAGMON
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setMAGMON(Date MAGMON) {
        this.MAGMON = MAGMON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.INIWAV
     *
     * @return the value of HG_APP_VASP_INCAR.INIWAV
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getINIWAV() {
        return INIWAV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.INIWAV
     *
     * @param INIWAV the value for HG_APP_VASP_INCAR.INIWAV
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setINIWAV(Integer INIWAV) {
        this.INIWAV = INIWAV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.ENCUT
     *
     * @return the value of HG_APP_VASP_INCAR.ENCUT
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Float getENCUT() {
        return ENCUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.ENCUT
     *
     * @param ENCUT the value for HG_APP_VASP_INCAR.ENCUT
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setENCUT(Float ENCUT) {
        this.ENCUT = ENCUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.PREC
     *
     * @return the value of HG_APP_VASP_INCAR.PREC
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public String getPREC() {
        return PREC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.PREC
     *
     * @param PREC the value for HG_APP_VASP_INCAR.PREC
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setPREC(String PREC) {
        this.PREC = PREC == null ? null : PREC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.NELM
     *
     * @return the value of HG_APP_VASP_INCAR.NELM
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getNELM() {
        return NELM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.NELM
     *
     * @param NELM the value for HG_APP_VASP_INCAR.NELM
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setNELM(Integer NELM) {
        this.NELM = NELM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.NELMIN
     *
     * @return the value of HG_APP_VASP_INCAR.NELMIN
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getNELMIN() {
        return NELMIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.NELMIN
     *
     * @param NELMIN the value for HG_APP_VASP_INCAR.NELMIN
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setNELMIN(Integer NELMIN) {
        this.NELMIN = NELMIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.MELMDL
     *
     * @return the value of HG_APP_VASP_INCAR.MELMDL
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getMELMDL() {
        return MELMDL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.MELMDL
     *
     * @param MELMDL the value for HG_APP_VASP_INCAR.MELMDL
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setMELMDL(Integer MELMDL) {
        this.MELMDL = MELMDL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.EDIFF
     *
     * @return the value of HG_APP_VASP_INCAR.EDIFF
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Float getEDIFF() {
        return EDIFF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.EDIFF
     *
     * @param EDIFF the value for HG_APP_VASP_INCAR.EDIFF
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setEDIFF(Float EDIFF) {
        this.EDIFF = EDIFF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.EDIFFG
     *
     * @return the value of HG_APP_VASP_INCAR.EDIFFG
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Float getEDIFFG() {
        return EDIFFG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.EDIFFG
     *
     * @param EDIFFG the value for HG_APP_VASP_INCAR.EDIFFG
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setEDIFFG(Float EDIFFG) {
        this.EDIFFG = EDIFFG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.NSW
     *
     * @return the value of HG_APP_VASP_INCAR.NSW
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getNSW() {
        return NSW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.NSW
     *
     * @param NSW the value for HG_APP_VASP_INCAR.NSW
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setNSW(Integer NSW) {
        this.NSW = NSW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.NBLOCK
     *
     * @return the value of HG_APP_VASP_INCAR.NBLOCK
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getNBLOCK() {
        return NBLOCK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.NBLOCK
     *
     * @param NBLOCK the value for HG_APP_VASP_INCAR.NBLOCK
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setNBLOCK(Integer NBLOCK) {
        this.NBLOCK = NBLOCK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.KBLOCK
     *
     * @return the value of HG_APP_VASP_INCAR.KBLOCK
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getKBLOCK() {
        return KBLOCK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.KBLOCK
     *
     * @param KBLOCK the value for HG_APP_VASP_INCAR.KBLOCK
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setKBLOCK(Integer KBLOCK) {
        this.KBLOCK = KBLOCK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.IBRION
     *
     * @return the value of HG_APP_VASP_INCAR.IBRION
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getIBRION() {
        return IBRION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.IBRION
     *
     * @param IBRION the value for HG_APP_VASP_INCAR.IBRION
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setIBRION(Integer IBRION) {
        this.IBRION = IBRION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.ISIF
     *
     * @return the value of HG_APP_VASP_INCAR.ISIF
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getISIF() {
        return ISIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.ISIF
     *
     * @param ISIF the value for HG_APP_VASP_INCAR.ISIF
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setISIF(Integer ISIF) {
        this.ISIF = ISIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.IWAVPR
     *
     * @return the value of HG_APP_VASP_INCAR.IWAVPR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getIWAVPR() {
        return IWAVPR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.IWAVPR
     *
     * @param IWAVPR the value for HG_APP_VASP_INCAR.IWAVPR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setIWAVPR(Integer IWAVPR) {
        this.IWAVPR = IWAVPR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.ISYM
     *
     * @return the value of HG_APP_VASP_INCAR.ISYM
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getISYM() {
        return ISYM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.ISYM
     *
     * @param ISYM the value for HG_APP_VASP_INCAR.ISYM
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setISYM(Integer ISYM) {
        this.ISYM = ISYM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.SYMPEREC
     *
     * @return the value of HG_APP_VASP_INCAR.SYMPEREC
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getSYMPEREC() {
        return SYMPEREC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.SYMPEREC
     *
     * @param SYMPEREC the value for HG_APP_VASP_INCAR.SYMPEREC
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setSYMPEREC(Integer SYMPEREC) {
        this.SYMPEREC = SYMPEREC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.LCORR
     *
     * @return the value of HG_APP_VASP_INCAR.LCORR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public String getLCORR() {
        return LCORR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.LCORR
     *
     * @param LCORR the value for HG_APP_VASP_INCAR.LCORR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setLCORR(String LCORR) {
        this.LCORR = LCORR == null ? null : LCORR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.POTIM
     *
     * @return the value of HG_APP_VASP_INCAR.POTIM
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Float getPOTIM() {
        return POTIM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.POTIM
     *
     * @param POTIM the value for HG_APP_VASP_INCAR.POTIM
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setPOTIM(Float POTIM) {
        this.POTIM = POTIM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.TEBEG
     *
     * @return the value of HG_APP_VASP_INCAR.TEBEG
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Float getTEBEG() {
        return TEBEG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.TEBEG
     *
     * @param TEBEG the value for HG_APP_VASP_INCAR.TEBEG
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setTEBEG(Float TEBEG) {
        this.TEBEG = TEBEG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.TEEND
     *
     * @return the value of HG_APP_VASP_INCAR.TEEND
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Float getTEEND() {
        return TEEND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.TEEND
     *
     * @param TEEND the value for HG_APP_VASP_INCAR.TEEND
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setTEEND(Float TEEND) {
        this.TEEND = TEEND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.SMASS
     *
     * @return the value of HG_APP_VASP_INCAR.SMASS
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getSMASS() {
        return SMASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.SMASS
     *
     * @param SMASS the value for HG_APP_VASP_INCAR.SMASS
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setSMASS(Integer SMASS) {
        this.SMASS = SMASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.NPACO
     *
     * @return the value of HG_APP_VASP_INCAR.NPACO
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getNPACO() {
        return NPACO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.NPACO
     *
     * @param NPACO the value for HG_APP_VASP_INCAR.NPACO
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setNPACO(Integer NPACO) {
        this.NPACO = NPACO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.APACO
     *
     * @return the value of HG_APP_VASP_INCAR.APACO
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getAPACO() {
        return APACO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.APACO
     *
     * @param APACO the value for HG_APP_VASP_INCAR.APACO
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setAPACO(Integer APACO) {
        this.APACO = APACO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.POMASS
     *
     * @return the value of HG_APP_VASP_INCAR.POMASS
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Float getPOMASS() {
        return POMASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.POMASS
     *
     * @param POMASS the value for HG_APP_VASP_INCAR.POMASS
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setPOMASS(Float POMASS) {
        this.POMASS = POMASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.ZVAL
     *
     * @return the value of HG_APP_VASP_INCAR.ZVAL
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Float getZVAL() {
        return ZVAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.ZVAL
     *
     * @param ZVAL the value for HG_APP_VASP_INCAR.ZVAL
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setZVAL(Float ZVAL) {
        this.ZVAL = ZVAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.RWIGS
     *
     * @return the value of HG_APP_VASP_INCAR.RWIGS
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Date getRWIGS() {
        return RWIGS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.RWIGS
     *
     * @param RWIGS the value for HG_APP_VASP_INCAR.RWIGS
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setRWIGS(Date RWIGS) {
        this.RWIGS = RWIGS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.NELECT
     *
     * @return the value of HG_APP_VASP_INCAR.NELECT
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Float getNELECT() {
        return NELECT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.NELECT
     *
     * @param NELECT the value for HG_APP_VASP_INCAR.NELECT
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setNELECT(Float NELECT) {
        this.NELECT = NELECT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.NUPDOWN
     *
     * @return the value of HG_APP_VASP_INCAR.NUPDOWN
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getNUPDOWN() {
        return NUPDOWN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.NUPDOWN
     *
     * @param NUPDOWN the value for HG_APP_VASP_INCAR.NUPDOWN
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setNUPDOWN(Integer NUPDOWN) {
        this.NUPDOWN = NUPDOWN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.EMIN
     *
     * @return the value of HG_APP_VASP_INCAR.EMIN
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Float getEMIN() {
        return EMIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.EMIN
     *
     * @param EMIN the value for HG_APP_VASP_INCAR.EMIN
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setEMIN(Float EMIN) {
        this.EMIN = EMIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.EMAX
     *
     * @return the value of HG_APP_VASP_INCAR.EMAX
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Float getEMAX() {
        return EMAX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.EMAX
     *
     * @param EMAX the value for HG_APP_VASP_INCAR.EMAX
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setEMAX(Float EMAX) {
        this.EMAX = EMAX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.ISMEAR
     *
     * @return the value of HG_APP_VASP_INCAR.ISMEAR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getISMEAR() {
        return ISMEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.ISMEAR
     *
     * @param ISMEAR the value for HG_APP_VASP_INCAR.ISMEAR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setISMEAR(Integer ISMEAR) {
        this.ISMEAR = ISMEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.SIGMA
     *
     * @return the value of HG_APP_VASP_INCAR.SIGMA
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Float getSIGMA() {
        return SIGMA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.SIGMA
     *
     * @param SIGMA the value for HG_APP_VASP_INCAR.SIGMA
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setSIGMA(Float SIGMA) {
        this.SIGMA = SIGMA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.ALGO
     *
     * @return the value of HG_APP_VASP_INCAR.ALGO
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public String getALGO() {
        return ALGO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.ALGO
     *
     * @param ALGO the value for HG_APP_VASP_INCAR.ALGO
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setALGO(String ALGO) {
        this.ALGO = ALGO == null ? null : ALGO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.IALGO
     *
     * @return the value of HG_APP_VASP_INCAR.IALGO
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getIALGO() {
        return IALGO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.IALGO
     *
     * @param IALGO the value for HG_APP_VASP_INCAR.IALGO
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setIALGO(Integer IALGO) {
        this.IALGO = IALGO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.LREAL
     *
     * @return the value of HG_APP_VASP_INCAR.LREAL
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public String getLREAL() {
        return LREAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.LREAL
     *
     * @param LREAL the value for HG_APP_VASP_INCAR.LREAL
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setLREAL(String LREAL) {
        this.LREAL = LREAL == null ? null : LREAL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.ROPT
     *
     * @return the value of HG_APP_VASP_INCAR.ROPT
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Date getROPT() {
        return ROPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.ROPT
     *
     * @param ROPT the value for HG_APP_VASP_INCAR.ROPT
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setROPT(Date ROPT) {
        this.ROPT = ROPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.GGA
     *
     * @return the value of HG_APP_VASP_INCAR.GGA
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public String getGGA() {
        return GGA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.GGA
     *
     * @param GGA the value for HG_APP_VASP_INCAR.GGA
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setGGA(String GGA) {
        this.GGA = GGA == null ? null : GGA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.VOSKOWN
     *
     * @return the value of HG_APP_VASP_INCAR.VOSKOWN
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getVOSKOWN() {
        return VOSKOWN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.VOSKOWN
     *
     * @param VOSKOWN the value for HG_APP_VASP_INCAR.VOSKOWN
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setVOSKOWN(Integer VOSKOWN) {
        this.VOSKOWN = VOSKOWN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.DIPOL
     *
     * @return the value of HG_APP_VASP_INCAR.DIPOL
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Date getDIPOL() {
        return DIPOL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.DIPOL
     *
     * @param DIPOL the value for HG_APP_VASP_INCAR.DIPOL
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setDIPOL(Date DIPOL) {
        this.DIPOL = DIPOL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.AMIX
     *
     * @return the value of HG_APP_VASP_INCAR.AMIX
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Float getAMIX() {
        return AMIX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.AMIX
     *
     * @param AMIX the value for HG_APP_VASP_INCAR.AMIX
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setAMIX(Float AMIX) {
        this.AMIX = AMIX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.BMIX
     *
     * @return the value of HG_APP_VASP_INCAR.BMIX
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Float getBMIX() {
        return BMIX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.BMIX
     *
     * @param BMIX the value for HG_APP_VASP_INCAR.BMIX
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setBMIX(Float BMIX) {
        this.BMIX = BMIX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.WEIMIN
     *
     * @return the value of HG_APP_VASP_INCAR.WEIMIN
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Float getWEIMIN() {
        return WEIMIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.WEIMIN
     *
     * @param WEIMIN the value for HG_APP_VASP_INCAR.WEIMIN
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setWEIMIN(Float WEIMIN) {
        this.WEIMIN = WEIMIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.EBREAK
     *
     * @return the value of HG_APP_VASP_INCAR.EBREAK
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Float getEBREAK() {
        return EBREAK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.EBREAK
     *
     * @param EBREAK the value for HG_APP_VASP_INCAR.EBREAK
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setEBREAK(Float EBREAK) {
        this.EBREAK = EBREAK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.DEPER
     *
     * @return the value of HG_APP_VASP_INCAR.DEPER
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Float getDEPER() {
        return DEPER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.DEPER
     *
     * @param DEPER the value for HG_APP_VASP_INCAR.DEPER
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setDEPER(Float DEPER) {
        this.DEPER = DEPER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.TIME
     *
     * @return the value of HG_APP_VASP_INCAR.TIME
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Float getTIME() {
        return TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.TIME
     *
     * @param TIME the value for HG_APP_VASP_INCAR.TIME
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setTIME(Float TIME) {
        this.TIME = TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.LWAVE
     *
     * @return the value of HG_APP_VASP_INCAR.LWAVE
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public String getLWAVE() {
        return LWAVE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.LWAVE
     *
     * @param LWAVE the value for HG_APP_VASP_INCAR.LWAVE
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setLWAVE(String LWAVE) {
        this.LWAVE = LWAVE == null ? null : LWAVE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.LCHARG
     *
     * @return the value of HG_APP_VASP_INCAR.LCHARG
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public String getLCHARG() {
        return LCHARG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.LCHARG
     *
     * @param LCHARG the value for HG_APP_VASP_INCAR.LCHARG
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setLCHARG(String LCHARG) {
        this.LCHARG = LCHARG == null ? null : LCHARG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.LVTOT
     *
     * @return the value of HG_APP_VASP_INCAR.LVTOT
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public String getLVTOT() {
        return LVTOT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.LVTOT
     *
     * @param LVTOT the value for HG_APP_VASP_INCAR.LVTOT
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setLVTOT(String LVTOT) {
        this.LVTOT = LVTOT == null ? null : LVTOT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.LVHAR
     *
     * @return the value of HG_APP_VASP_INCAR.LVHAR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public String getLVHAR() {
        return LVHAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.LVHAR
     *
     * @param LVHAR the value for HG_APP_VASP_INCAR.LVHAR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setLVHAR(String LVHAR) {
        this.LVHAR = LVHAR == null ? null : LVHAR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.LELF
     *
     * @return the value of HG_APP_VASP_INCAR.LELF
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public String getLELF() {
        return LELF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.LELF
     *
     * @param LELF the value for HG_APP_VASP_INCAR.LELF
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setLELF(String LELF) {
        this.LELF = LELF == null ? null : LELF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.LORBIT
     *
     * @return the value of HG_APP_VASP_INCAR.LORBIT
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public String getLORBIT() {
        return LORBIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.LORBIT
     *
     * @param LORBIT the value for HG_APP_VASP_INCAR.LORBIT
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setLORBIT(String LORBIT) {
        this.LORBIT = LORBIT == null ? null : LORBIT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.NPAR
     *
     * @return the value of HG_APP_VASP_INCAR.NPAR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public Integer getNPAR() {
        return NPAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.NPAR
     *
     * @param NPAR the value for HG_APP_VASP_INCAR.NPAR
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setNPAR(Integer NPAR) {
        this.NPAR = NPAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.LSCALAPACK
     *
     * @return the value of HG_APP_VASP_INCAR.LSCALAPACK
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public String getLSCALAPACK() {
        return LSCALAPACK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.LSCALAPACK
     *
     * @param LSCALAPACK the value for HG_APP_VASP_INCAR.LSCALAPACK
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setLSCALAPACK(String LSCALAPACK) {
        this.LSCALAPACK = LSCALAPACK == null ? null : LSCALAPACK.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.LSCALU
     *
     * @return the value of HG_APP_VASP_INCAR.LSCALU
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public String getLSCALU() {
        return LSCALU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.LSCALU
     *
     * @param LSCALU the value for HG_APP_VASP_INCAR.LSCALU
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setLSCALU(String LSCALU) {
        this.LSCALU = LSCALU == null ? null : LSCALU.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HG_APP_VASP_INCAR.LASYNC
     *
     * @return the value of HG_APP_VASP_INCAR.LASYNC
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public String getLASYNC() {
        return LASYNC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HG_APP_VASP_INCAR.LASYNC
     *
     * @param LASYNC the value for HG_APP_VASP_INCAR.LASYNC
     *
     * @mbg.generated Wed Dec 12 19:24:28 CST 2018
     */
    public void setLASYNC(String LASYNC) {
        this.LASYNC = LASYNC == null ? null : LASYNC.trim();
    }
}