package hpcgateway.wp.apps.materials.beans;

import java.math.BigDecimal;
import java.util.Date;

public class HpcCloudUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HPC_CLOUD_USER.HPC_USER_ID
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    private Long HPC_USER_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HPC_CLOUD_USER.HPC_USER_NAME
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    private String HPC_USER_NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HPC_CLOUD_USER.HPC_USER_PASSWD
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    private String HPC_USER_PASSWD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HPC_CLOUD_USER.HPC_USER_ASKTO
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    private Long HPC_USER_ASKTO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HPC_CLOUD_USER.HPC_USER_BALANCE
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    private BigDecimal HPC_USER_BALANCE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HPC_CLOUD_USER.HPC_USER_CHARGED
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    private BigDecimal HPC_USER_CHARGED;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HPC_CLOUD_USER.HPC_USER_CONSUMED
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    private BigDecimal HPC_USER_CONSUMED;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HPC_CLOUD_USER.HPC_USER_JOB_FEE
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    private BigDecimal HPC_USER_JOB_FEE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HPC_CLOUD_USER.HPC_USER_JOB_NUM
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    private Long HPC_USER_JOB_NUM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HPC_CLOUD_USER.HPC_USER_JOB_HOSTS
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    private Long HPC_USER_JOB_HOSTS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HPC_CLOUD_USER.HPC_USER_JOB_CORES
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    private Long HPC_USER_JOB_CORES;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HPC_CLOUD_USER.HPC_USER_JOB_TIME
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    private Date HPC_USER_JOB_TIME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HPC_CLOUD_USER.HPC_USER_STORAGE_FEE
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    private BigDecimal HPC_USER_STORAGE_FEE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HPC_CLOUD_USER.HPC_USER_STORAGE_CAP
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    private BigDecimal HPC_USER_STORAGE_CAP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HPC_CLOUD_USER.HPC_USER_STORAGE_UNIT
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    private String HPC_USER_STORAGE_UNIT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HPC_CLOUD_USER.HPC_USER_STORAGE_TIME
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    private Date HPC_USER_STORAGE_TIME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HPC_CLOUD_USER.HPC_USER_ID
     *
     * @return the value of HPC_CLOUD_USER.HPC_USER_ID
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public Long getHPC_USER_ID() {
        return HPC_USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HPC_CLOUD_USER.HPC_USER_ID
     *
     * @param HPC_USER_ID the value for HPC_CLOUD_USER.HPC_USER_ID
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public void setHPC_USER_ID(Long HPC_USER_ID) {
        this.HPC_USER_ID = HPC_USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HPC_CLOUD_USER.HPC_USER_NAME
     *
     * @return the value of HPC_CLOUD_USER.HPC_USER_NAME
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public String getHPC_USER_NAME() {
        return HPC_USER_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HPC_CLOUD_USER.HPC_USER_NAME
     *
     * @param HPC_USER_NAME the value for HPC_CLOUD_USER.HPC_USER_NAME
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public void setHPC_USER_NAME(String HPC_USER_NAME) {
        this.HPC_USER_NAME = HPC_USER_NAME == null ? null : HPC_USER_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HPC_CLOUD_USER.HPC_USER_PASSWD
     *
     * @return the value of HPC_CLOUD_USER.HPC_USER_PASSWD
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public String getHPC_USER_PASSWD() {
        return HPC_USER_PASSWD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HPC_CLOUD_USER.HPC_USER_PASSWD
     *
     * @param HPC_USER_PASSWD the value for HPC_CLOUD_USER.HPC_USER_PASSWD
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public void setHPC_USER_PASSWD(String HPC_USER_PASSWD) {
        this.HPC_USER_PASSWD = HPC_USER_PASSWD == null ? null : HPC_USER_PASSWD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HPC_CLOUD_USER.HPC_USER_ASKTO
     *
     * @return the value of HPC_CLOUD_USER.HPC_USER_ASKTO
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public Long getHPC_USER_ASKTO() {
        return HPC_USER_ASKTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HPC_CLOUD_USER.HPC_USER_ASKTO
     *
     * @param HPC_USER_ASKTO the value for HPC_CLOUD_USER.HPC_USER_ASKTO
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public void setHPC_USER_ASKTO(Long HPC_USER_ASKTO) {
        this.HPC_USER_ASKTO = HPC_USER_ASKTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HPC_CLOUD_USER.HPC_USER_BALANCE
     *
     * @return the value of HPC_CLOUD_USER.HPC_USER_BALANCE
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public BigDecimal getHPC_USER_BALANCE() {
        return HPC_USER_BALANCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HPC_CLOUD_USER.HPC_USER_BALANCE
     *
     * @param HPC_USER_BALANCE the value for HPC_CLOUD_USER.HPC_USER_BALANCE
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public void setHPC_USER_BALANCE(BigDecimal HPC_USER_BALANCE) {
        this.HPC_USER_BALANCE = HPC_USER_BALANCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HPC_CLOUD_USER.HPC_USER_CHARGED
     *
     * @return the value of HPC_CLOUD_USER.HPC_USER_CHARGED
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public BigDecimal getHPC_USER_CHARGED() {
        return HPC_USER_CHARGED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HPC_CLOUD_USER.HPC_USER_CHARGED
     *
     * @param HPC_USER_CHARGED the value for HPC_CLOUD_USER.HPC_USER_CHARGED
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public void setHPC_USER_CHARGED(BigDecimal HPC_USER_CHARGED) {
        this.HPC_USER_CHARGED = HPC_USER_CHARGED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HPC_CLOUD_USER.HPC_USER_CONSUMED
     *
     * @return the value of HPC_CLOUD_USER.HPC_USER_CONSUMED
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public BigDecimal getHPC_USER_CONSUMED() {
        return HPC_USER_CONSUMED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HPC_CLOUD_USER.HPC_USER_CONSUMED
     *
     * @param HPC_USER_CONSUMED the value for HPC_CLOUD_USER.HPC_USER_CONSUMED
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public void setHPC_USER_CONSUMED(BigDecimal HPC_USER_CONSUMED) {
        this.HPC_USER_CONSUMED = HPC_USER_CONSUMED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HPC_CLOUD_USER.HPC_USER_JOB_FEE
     *
     * @return the value of HPC_CLOUD_USER.HPC_USER_JOB_FEE
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public BigDecimal getHPC_USER_JOB_FEE() {
        return HPC_USER_JOB_FEE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HPC_CLOUD_USER.HPC_USER_JOB_FEE
     *
     * @param HPC_USER_JOB_FEE the value for HPC_CLOUD_USER.HPC_USER_JOB_FEE
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public void setHPC_USER_JOB_FEE(BigDecimal HPC_USER_JOB_FEE) {
        this.HPC_USER_JOB_FEE = HPC_USER_JOB_FEE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HPC_CLOUD_USER.HPC_USER_JOB_NUM
     *
     * @return the value of HPC_CLOUD_USER.HPC_USER_JOB_NUM
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public Long getHPC_USER_JOB_NUM() {
        return HPC_USER_JOB_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HPC_CLOUD_USER.HPC_USER_JOB_NUM
     *
     * @param HPC_USER_JOB_NUM the value for HPC_CLOUD_USER.HPC_USER_JOB_NUM
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public void setHPC_USER_JOB_NUM(Long HPC_USER_JOB_NUM) {
        this.HPC_USER_JOB_NUM = HPC_USER_JOB_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HPC_CLOUD_USER.HPC_USER_JOB_HOSTS
     *
     * @return the value of HPC_CLOUD_USER.HPC_USER_JOB_HOSTS
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public Long getHPC_USER_JOB_HOSTS() {
        return HPC_USER_JOB_HOSTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HPC_CLOUD_USER.HPC_USER_JOB_HOSTS
     *
     * @param HPC_USER_JOB_HOSTS the value for HPC_CLOUD_USER.HPC_USER_JOB_HOSTS
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public void setHPC_USER_JOB_HOSTS(Long HPC_USER_JOB_HOSTS) {
        this.HPC_USER_JOB_HOSTS = HPC_USER_JOB_HOSTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HPC_CLOUD_USER.HPC_USER_JOB_CORES
     *
     * @return the value of HPC_CLOUD_USER.HPC_USER_JOB_CORES
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public Long getHPC_USER_JOB_CORES() {
        return HPC_USER_JOB_CORES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HPC_CLOUD_USER.HPC_USER_JOB_CORES
     *
     * @param HPC_USER_JOB_CORES the value for HPC_CLOUD_USER.HPC_USER_JOB_CORES
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public void setHPC_USER_JOB_CORES(Long HPC_USER_JOB_CORES) {
        this.HPC_USER_JOB_CORES = HPC_USER_JOB_CORES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HPC_CLOUD_USER.HPC_USER_JOB_TIME
     *
     * @return the value of HPC_CLOUD_USER.HPC_USER_JOB_TIME
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public Date getHPC_USER_JOB_TIME() {
        return HPC_USER_JOB_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HPC_CLOUD_USER.HPC_USER_JOB_TIME
     *
     * @param HPC_USER_JOB_TIME the value for HPC_CLOUD_USER.HPC_USER_JOB_TIME
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public void setHPC_USER_JOB_TIME(Date HPC_USER_JOB_TIME) {
        this.HPC_USER_JOB_TIME = HPC_USER_JOB_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HPC_CLOUD_USER.HPC_USER_STORAGE_FEE
     *
     * @return the value of HPC_CLOUD_USER.HPC_USER_STORAGE_FEE
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public BigDecimal getHPC_USER_STORAGE_FEE() {
        return HPC_USER_STORAGE_FEE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HPC_CLOUD_USER.HPC_USER_STORAGE_FEE
     *
     * @param HPC_USER_STORAGE_FEE the value for HPC_CLOUD_USER.HPC_USER_STORAGE_FEE
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public void setHPC_USER_STORAGE_FEE(BigDecimal HPC_USER_STORAGE_FEE) {
        this.HPC_USER_STORAGE_FEE = HPC_USER_STORAGE_FEE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HPC_CLOUD_USER.HPC_USER_STORAGE_CAP
     *
     * @return the value of HPC_CLOUD_USER.HPC_USER_STORAGE_CAP
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public BigDecimal getHPC_USER_STORAGE_CAP() {
        return HPC_USER_STORAGE_CAP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HPC_CLOUD_USER.HPC_USER_STORAGE_CAP
     *
     * @param HPC_USER_STORAGE_CAP the value for HPC_CLOUD_USER.HPC_USER_STORAGE_CAP
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public void setHPC_USER_STORAGE_CAP(BigDecimal HPC_USER_STORAGE_CAP) {
        this.HPC_USER_STORAGE_CAP = HPC_USER_STORAGE_CAP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HPC_CLOUD_USER.HPC_USER_STORAGE_UNIT
     *
     * @return the value of HPC_CLOUD_USER.HPC_USER_STORAGE_UNIT
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public String getHPC_USER_STORAGE_UNIT() {
        return HPC_USER_STORAGE_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HPC_CLOUD_USER.HPC_USER_STORAGE_UNIT
     *
     * @param HPC_USER_STORAGE_UNIT the value for HPC_CLOUD_USER.HPC_USER_STORAGE_UNIT
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public void setHPC_USER_STORAGE_UNIT(String HPC_USER_STORAGE_UNIT) {
        this.HPC_USER_STORAGE_UNIT = HPC_USER_STORAGE_UNIT == null ? null : HPC_USER_STORAGE_UNIT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HPC_CLOUD_USER.HPC_USER_STORAGE_TIME
     *
     * @return the value of HPC_CLOUD_USER.HPC_USER_STORAGE_TIME
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public Date getHPC_USER_STORAGE_TIME() {
        return HPC_USER_STORAGE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HPC_CLOUD_USER.HPC_USER_STORAGE_TIME
     *
     * @param HPC_USER_STORAGE_TIME the value for HPC_CLOUD_USER.HPC_USER_STORAGE_TIME
     *
     * @mbg.generated Thu Nov 22 06:58:51 CST 2018
     */
    public void setHPC_USER_STORAGE_TIME(Date HPC_USER_STORAGE_TIME) {
        this.HPC_USER_STORAGE_TIME = HPC_USER_STORAGE_TIME;
    }
}